$set 3 #Configmenu

$ #ConfigOptions
# 設定オプション
$ #FocusModel
# フォーカスモデル
$ #WindowPlacement
# ウィンドウ配置
$ #ImageDithering
# 画像ディザ
$ #OpaqueMove
# ウィンドウの内容を表示したまま移動
$ #FullMax
# 完全最大化(タスクバー無視)
$ #FocusNew
# 新規ウィンドウにフォーカス
$ #FocusLast
# ワークスペース移動時に最後のウィンドウにフォーカス
$ #ClickToFocus
# クリックでフォーカス
$ #SloppyFocus
# カーソルオーバーでフォーカス
$ #AutoRaise
# フォーカスを当てたときに最前面に移動
$ #SmartRows
# 賢く配置 (行:ROW)
$ #SmartCols
# 賢く配置 (列:COL)
$ #Cascade
# カスケード配置
$ #LeftRight
# 左から右へ
$ #RightLeft
# 右から左へ
$ #TopBottom
# 上から下へ
$ #BottomTop
# 下から上へ
$ #Tabs
# タブを表示
$ #Icons
# アイコンの表示
$ #TabPlacement
# タブの表示位置
$ #TabRotateVertical
# タブの自動回転
$ #SemiSloppyFocus
# カーソルオーバーでフォーカス(SemiSloppy)
$ #MaxOverSlit
# Slitを越えて最大化
$ #SloppyWindowGrouping
# Window内にタブドロップでもタブグループに
$ #WorkspaceWarping
# ウィンドウドラッグでワークスペースを移動
$ #DesktopWheeling
# マウスホイールでワークスペース切り換え
