.\"     Title: fluxbox
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.74.0 <http://docbook.sf.net/>
.\"      Date: 10/04/2008
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "FLUXBOX" "1" "10/04/2008" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * (re)Define some macros
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" toupper - uppercase a string (locale-aware)
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de toupper
.tr aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ
\\$*
.tr aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz
..
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" SH-xref - format a cross-reference to an SH section
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de SH-xref
.ie n \{\
.\}
.toupper \\$*
.el \{\
\\$*
.\}
..
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" SH - level-one heading that works better for non-TTY output
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de1 SH
.\" put an extra blank line of space above the head in non-TTY output
.if t \{\
.sp 1
.\}
.sp \\n[PD]u
.nr an-level 1
.set-an-margin
.nr an-prevailing-indent \\n[IN]
.fi
.in \\n[an-margin]u
.ti 0
.HTML-TAG ".NH \\n[an-level]"
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
\." make the size of the head bigger
.ps +3
.ft B
.ne (2v + 1u)
.ie n \{\
.\" if n (TTY output), use uppercase
.toupper \\$*
.\}
.el \{\
.nr an-break-flag 0
.\" if not n (not TTY), use normal case (not uppercase)
\\$1
.in \\n[an-margin]u
.ti 0
.\" if not n (not TTY), put a border/line under subheading
.sp -.6
\l'\n(.lu'
.\}
..
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" SS - level-two heading that works better for non-TTY output
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de1 SS
.sp \\n[PD]u
.nr an-level 1
.set-an-margin
.nr an-prevailing-indent \\n[IN]
.fi
.in \\n[IN]u
.ti \\n[SN]u
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.ps \\n[PS-SS]u
\." make the size of the head bigger
.ps +2
.ft B
.ne (2v + 1u)
.if \\n[.$] \&\\$*
..
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" BB/BE - put background/screen (filled box) around block of text
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de BB
.if t \{\
.sp -.5
.br
.in +2n
.ll -2n
.gcolor red
.di BX
.\}
..
.de EB
.if t \{\
.if "\\$2"adjust-for-leading-newline" \{\
.sp -1
.\}
.br
.di
.in
.ll
.gcolor
.nr BW \\n(.lu-\\n(.i
.nr BH \\n(dn+.5v
.ne \\n(BHu+.5v
.ie "\\$2"adjust-for-leading-newline" \{\
\M[\\$1]\h'1n'\v'+.5v'\D'P \\n(BWu 0 0 \\n(BHu -\\n(BWu 0 0 -\\n(BHu'\M[]
.\}
.el \{\
\M[\\$1]\h'1n'\v'-.5v'\D'P \\n(BWu 0 0 \\n(BHu -\\n(BWu 0 0 -\\n(BHu'\M[]
.\}
.in 0
.sp -.5v
.nf
.BX
.in
.sp .5v
.fi
.\}
..
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" BM/EM - put colored marker in margin next to block of text
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de BM
.if t \{\
.br
.ll -2n
.gcolor red
.di BX
.\}
..
.de EM
.if t \{\
.br
.di
.ll
.gcolor
.nr BH \\n(dn
.ne \\n(BHu
\M[\\$1]\D'P -.75n 0 0 \\n(BHu -(\\n[.i]u - \\n(INu - .75n) 0 0 -\\n(BHu'\M[]
.in 0
.nf
.BX
.in
.fi
.\}
..
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "Name"
fluxbox \- A lightweight window manager for the X Windowing System
.SH "Synopsis"
.sp
\fIfluxbox\fR [\-rc rcfile] [\-log logfile] [\-display display] [\-screen scr,scr|all] [\-verbose] [\-sync]
.sp
\fIfluxbox\fR [\-v | \-version] | [\-h | \-help] | [\-i | \-info] | [\-list\-commands]
.SH "DESCRIPTION"
.sp
fluxbox(1) provides configurable window decorations, a root menu to launch applications and a toolbar that shows the current workspace name, a set of application names and the current time\&. There is also a workspace menu to add or remove workspaces\&. The `slit\' can be used to dock small applications; e\&.g\&. most of the bbtools can use the slit\&.
.sp
fluxbox(1) can iconify windows to the toolbar, in addition to adding the window to the \fIIcons\fR submenu of the workspace menu\&. One click and they reappear\&. A double\-click on the titlebar of the window will \fIshade\fR it; i\&.e\&. the window will disappear, and only the titlebar will remain visible\&.
.sp
fluxbox(1) uses its own graphics class to render its images on the fly\&. By using style files, you can determine in great detail how your desktop looks\&. fluxbox styles are compatible with those of Blackbox 0\&.65 or earlier versions, so users migrating can still use their current favourite themes\&.
.sp
fluxbox(1) supports the majority of the Extended Window Manager Hints (EWMH) specification, as well as numerous other Window Hinting standards\&. This allows all compliant window managers to provide a common interface to standard features used by applications and desktop utilities\&.
.SH "OPTIONS"
.PP
\-display display
.RS 4
Start fluxbox on the specified display\&. Programs started by fluxbox will share the DISPLAY environment variable also\&.
.RE
.PP
\-h, \-help
.RS 4
Display command line options\&.
.RE
.PP
\-i, \-info
.RS 4
Display useful information concerning the defaults and compiled\-in options\&.
.RE
.PP
\-log logfile
.RS 4
Starting fluxbox with this option will designate a file in which you want to log events to\&.
.RE
.PP
\-rc rcfile
.RS 4
Use a different config file other than the default ~/\&.fluxbox/init\&.
.RE
.PP
\-v, \-version
.RS 4
The version of fluxbox installed\&.
.RE
.PP
\-screen scr,scr|all
.RS 4
Run on specified screens only or all (by default)\&.
.RE
.PP
\-verbose
.RS 4
Print more information in process\&.
.RE
.PP
\-sync
.RS 4
Synchronize with the X server for debugging\&.
.RE
.SH "STARTING FLUXBOX"
.sp
fluxbox(1) comes with a program called startfluxbox(8) usually located wherever you installed fluxbox\&. This script provides you with many options and variables that can be set when starting fluxbox\&. To actually call fluxbox and begin using it, you should place "exec startfluxbox" in your /\&.xinitrc or /\&.xsession (depending on your distribution and/or display manager) as the last executed command\&. This is assuming that the location of fluxbox(1) and startfluxbox(8) are in your shell\'s $PATH\&. Also note that you may need to create the /\&.xinitrc file or your setup may use /\&.xsession instead, depending on your X setup\&. For more information on your shell, please visit your shell\'s manual page\&.
.sp
By using fluxbox \-i you\'ll see the defaults used by fluxbox(1)\&. These are what fluxbox looks for upon startup\&. In the list of `Defaults:\' you\'ll see a menu file location, this is where you can provide a system\-wide menu file for your users\&.
.sp
On exit or restart, fluxbox will save user defaults in the file ~/\&.fluxbox/init\&. Resources in this file can be edited by hand\&. fluxbox also has many tools to edit these; look through the main menu once fluxbox has started to find different ways of managing your session\&.
.SH "USING FLUXBOX"
.sp
When using fluxbox for the first time, users who are more accustomed to full desktop environments such as KDE or Gnome may be a little surprised by the minimal screen content\&. fluxbox is designed to be fast and powerful, so it may take a bit of getting used to \(em however, the rewards are worthwhile\&.
.sp
In this section, we\'ll give a quick summary of the common things\&. However, we recommend that you consult the referenced sections of this manual to further develop your understanding of what you can do with fluxbox\&.
.SS "Root Window (Main)"
.sp
Looking at the fluxbox desktop immediately after startup you\'ll generally see only one thing: the toolbar\&. If you right click (mouse button 3) somewhere on the desktop, you can access the RootMenu\&. A middle click (mouse button 2) on the desktop shows you the WorkspaceMenu\&.
.SS "RootMenu and WorkspaceMenu"
.sp
From the RootMenu you can launch applications and configure fluxbox\&. The WorkspaceMenu shows all windows and on which workspaces they are\&. See section MENUS on how to customize these menus\&.
.SS "Toolbar"
.sp
The toolbar contains any combination of the following tools:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBWorkspace Name\fR: Name of the current visible workspace
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBIconbar\fR: List of windows managed by fluxbox
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBSystem Tray\fR: Area for applets
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBClock\fR: Date and Time
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBWorkspace Arrows\fR: Previous/Next Workspace
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBWindow Arrows\fR: Previous/Next Application Window
.RE
.sp
The contents of the toolbar can be configured in the `init\' file\&. We discuss the `init\' file at great length in the RESOURCES section\&.
.SS "Slit"
.sp
Initially you won\'t be able to see the slit\&. It is there, but it isn\'t being used yet\&. The slit confuses some people initially\&. Think of it as a dock where you can place smaller programs\&. If you\'ve looked at any screenshots on the official fluxbox web site, you will have noticed some small programs on the edge of some of the screens\&. These were more than likely docked programs in the slit\&. To learn more about the slit, we have an entire section below that goes into detail about the options you have\&.
.SS "Layers"
.sp
fluxbox manages the following layers (from highest to lowest):
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Above Dock
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Dock
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Top
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Normal
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Bottom
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Desktop
.RE
.sp
Windows on a higher layer will always appear above those on a lower one\&. These layers can be used on application windows, the slit or the toolbar\&. You can assign applications to a certain layer by specifying it in the `apps\' file or through the WindowMenu\&. We discuss the `apps\' file in the APPLICATIONS section\&. We discuss the WindowMenu in the MENUS section\&. We discuss layers in more detail in the LAYERS section\&.
.SS "Focus Model"
.sp
The window that has the focus is the one that receives key and mouse events\&. The focus model is selectable via the Configuration menu located in the root menu\&. We\'ll discuss the different types of focus below in the FOCUS MODEL section\&.
.SS "Windows"
.sp
A left click (mouse button 1) on any part of the window\'s border will raise it\&. Dragging then moves the window to another part of the desktop\&. A right click and drag on the border resizes the window\&. Dragging the resize grips at the left and right bottom corners also will resize the window\&. Middle clicking on a border or titlebar will immediately lower the window\&. Right clicking on the titlebar opens the Window menu\&. The commands unique to this menu are discussed in detail in the Window Menu section of MENUS\&.
.SS "Tabs"
.sp
fluxbox allows windows to be `grouped\' by middle clicking and holding on a window\'s tab and dragging it onto another window\&. This `tabbing\' allows you to put multiple applications in one location on the desktop and do several operations (for example, moving or resizing) to all windows in the group\&. By default, tabs are located just above the window, but they may be embedded in the titlebar or moved to other locations on the outside of the window\&. Configuration is discussed in TAB OPTIONS section\&.
.SH "MENUS"
.sp
fluxbox installs a default menu file in @pkgdatadir@/menu\&. You can also use fluxbox \-i to confirm this action\&. Of course this system\-wide menu can be customized for all users at once, but it is also possible to create an individual menu file for each user\&. By convention, users create a menu file in ~/\&.fluxbox/menu \&. Once you\'ve created your own menu file, you\'ll want to make sure that you properly declare this location in your `init\' file so that fluxbox knows where to look\&. The value you\'ll want to add or change is:
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
session\&.menuFile: <menufile>
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.sp
For this change to take effect, fluxbox must be restarted\&. Be sure that your menu is usable, then choose `Restart\' from the default fluxbox root menu\&. This restart is only necessary if you make changes to the `init\' file; otherwise, fluxbox will automatically detect your changes\&.
.SS "Root Menu"
.sp
The root menu is where you can change different aspects of fluxbox by simply clicking on a menu item\&. Most of the changes in this menu can also be done in the `init\' file\&. However it makes it very easy to change certain options without having to open up an editor and find the resource\&. In the root menu, you usually have a `fluxbox menu\' or `Settings\' submenu, where you will find lots of different options\&. We\'ll take a look at most, if not all, of those here\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBConfigure\fR: The next level under this menu is where you can set certain resources and really begin to customize the look and feel of your desktop\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBSystem Styles\fR: This is where the standard styles are listed\&. You can select one of these by clicking on it\&. You may have to `reload\' the config or `restart\' to get every graphical element to change to the new style\&. System styles are located in @pkgdatadir@/styles/ upon a default install\&. Remember that you can confirm this with fluxbox \-i\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBUser Styles\fR: ~/\&.fluxbox/styles This is the location where you will store new styles that you grab from the Internet\&. If you create your own styles this is also where you will put yours (provided that you follow the
\fIstandards\fR
described in fluxstyle(1))\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBWorkspace List\fR: This is a list of the workspaces configured in your `init\' file\&. If there are programs running on any of the workspaces, they will be listed one level down\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBTools\fR: Listed here are different tools that you can use\&. You can rename your workspace, run programs from a command line or regenerate your menu\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBWindow\fR: Allows you to switch your window manager\&. (Only listed if you have other window managers/desktop environments installed\&.)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBLock Screen\fR: Locks the screen\&...
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBfluxbox Command\fR: A little Commandline will popup where you can enter a fluxbox command\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBReload Config\fR: Use this to reload any menu files or style files\&. Just a basic re\-read of the files by a running fluxbox\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBRestart\fR: Restart the whole darn thing\&. This starts a completely new fluxbox process, rereads files and redraws all graphical elements\&. Running applications will remain open, however\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
*Exit: Exits fluxbox and probably shuts down the X Window server\&.
.RE
.SS "Configuration Menu"
.sp
This menu offers the opportunity to set up fluxbox\&. It contains many options from the init file, but this is an easier and faster way for most users\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBFocus Model\fR: Please read the FOCUS MODEL section at the end of this manual\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBTab Options\fR: Lets you configure the properties of tabs\&. Detailed in TAB OPTIONS section\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBSlit\fR: This Menu can be opened by right clicking the slit (if visible)\&. Find more information about this menu\'s options in the SLIT section\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBToolbar\fR: Please take a look at the "Configuration via the Toolbar Menu" part of the TOOLBAR section\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBTransparency\fR: This sets the transparency for a focused, unfocused window and the menu\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBOpaque Window Moving\fR: If enabled, you will see the window content while dragging it\&. Otherwise the window will be shown as a "border"\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBFull Maximization\fR: Enabling this will override the separate settings for the slit/toolbar\&. Windows will always maximize over/under both of them\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBFocus New Window\fR: If enabled, a newly opened window will gain focus\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBWindows Warping\fR: If enabled, you can drag windows from one workspace to another\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBClick Raises\fR: If enabled a click anywhere on a window area (including the decorations) will raise it\&. Otherwise you can only raise it by clicking the titlebar\&.
.RE
.SS "Window Menu"
.sp
The Window menu is displayed when you right click on the titlebar of a window\&. The options available are:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBSend To\&...\fR: Send window to another workspace\&. When you select the workspace with a middle click, fluxbox will send you along with the application to the selected workspace\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBShade\fR: Shade the window (display the titlebar only)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBIconify\fR: Iconify window\&. The `icon\' can be found in the Icons submenu of the workspace menu as well as in the toolbar (if a Toolbar mode showing Icons is selected)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBMaximize\fR: (Un)Maximize window\&. Depending on your toolbar and slit configuration, maximize may cover them\&. You can use the different mouse buttons for different aspects of maximize function\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Button 1 (Un)Maximize as normal\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Button 2 (Un)Maximize window vertically\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Button 3 (Un)Maximize window horizontally\&.
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBRaise\fR: Raise the window\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBLower\fR: Lower the window\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBStick\fR: (Un)Stick window\&. A `stuck\' window will always be displayed on all workspaces\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBLayer\&...\fR: Change the layer of this window\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBRemember\&...\fR: Specify which window settings should be stored in the apps file, covered later on in the APPLICATIONS section\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBClose\fR: Close the application softly\&.
.RE
.SS "Workspace Menu"
.sp
The workspace menu can be found by middle clicking on the background\&. A menu will popup giving you the option to add or remove a workspace\&. You will also see your workspaces listed there; middle clicking on a workspace name will take you to that workspace, whereas clicking on a window name in one of the per\-workspace submenus will take you to the workspace that window is on, and select the window\&. Last but not least you will notice the Icons menu\&. This is for applications which have been `iconified\'\&.
.SS "Menu Behavior"
.sp
The behavior of the submenus in a menu can be configured in the `init\' file, with the following entries (default for both is 0):
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
session\&.screen0\&.menuDelay: <msec>
session\&.screen0\&.menuDelayClose: <msec>
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.SS "Menu Syntax"
.sp
There are up to four fields in a menu line\&. They are of the form:
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
[tag] (label|filename) {command|filename} <icon file>
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.sp
The supported tags are:
.PP
[begin] (label)
.RS 4
This tells fluxbox to start parsing the menu file\&. This tag is required for fluxbox to read your menu file\&. If it cannot find it, the system default menu is used in its place\&.
.RE
.PP
[config] (label)
.RS 4
Inserts a fluxbox native submenu item, containing numerous configuration options concerning window placement, focus style, window moving style, etc\&.
.RE
.PP
[end]
.RS 4
This tells fluxbox that it is at the end of a menu\&. This can either be a submenu or the main root menu\&. There must be at least one of these tags in your menu to correspond to the required [begin] tag\&.
.RE
.PP
[exec] (label) {command}
.RS 4
Inserts a command item into the menu\&. When you select the menu item from the menu, fluxbox runs
\fIcommand\fR\&.
.RE
.PP
[exit] (label)
.RS 4
Inserts an item that shuts down and exits fluxbox\&. Any open windows are reparented to the root window before fluxbox exits\&.
.RE
.PP
[include] (file\-or\-directory\-name)
.RS 4
Parses the file specified by filename inline with the current menu\&. The filename can be the full path to a file or it can begin with ~/, which will be expanded into your home directory\&. If the path is a directory, then all files in the directory are included\&.
.RE
.PP
[nop] (label)
.RS 4
Insert a non\-operational item into the current menu\&. This can be used to help format the menu into blocks or sections if so desired\&. This tag does support a label, but one is not required in which case a blank item will be used instead\&.
.RE
.PP
[separator]
.RS 4
This will create a nice separation line\&. Useful for splitting up sections in a
\fIpretty\fR
way\&.
.RE
.PP
[style] (label) {filename}
.RS 4
This tells fluxbox to insert an item that, when selected, reads style file named filename and apply the new textures, colors and fonts to the current running session\&.
.RE
.PP
[stylesmenu] (directory)
.RS 4
Reads all filenames from the specified directory, assuming that they are all valid style files, and creates menu items in the current menu for every filename, that, when selected by the user will apply the selected style file to the current session\&. The labels that are created in the menu are the filenames of the style files\&.
.RE
.PP
[stylesdir] (label) {directory}
.RS 4
Creates a submenu entry with label (that is also the title of the new submenu), and inserts in that submenu all filenames in the specified directory, assuming that they are all valid style files (directories are ignored) in the same way as the [stylesdir] command does\&. Both [stylesdir] and [stylesmenu] commands make it possible to install style files without editing your init file\&.
.RE
.PP
[submenu] (label) {menutitle}
.RS 4
This tells fluxbox to create and parse a new menu\&. This menu is inserted as a submenu into the parent menu\&. These menus are parsed recursively, so there is no limit to the number of levels or nested submenus you can have\&. The title for the new menu is optional, if none is supplied, the new menu\'s title is the same as the item label\&. An [end] tag is required to end the submenu\&.
.RE
.PP
[reconfig] (label)
.RS 4
When selected this item re\-reads the current style and menu files and applies any changes\&. This is useful for creating a new style or theme, as you don\'t have to constantly restart fluxbox every time you save your style\&. However, fluxbox automatically rereads the menu whenever it changes\&.
.RE
.PP
[restart] (label) {command}
.RS 4
This tells fluxbox to restart\&. If command is supplied, it shuts down and runs the command (which is commonly the name of another window manager)\&. If the command is omitted, fluxbox restarts itself\&.
.RE
.PP
[wallpapers] (directory) {command}
.RS 4
This inserts a menu item to set the wallpaper for each file in the given directory\&. The command is optional and defaults to fbsetbg\&.
.RE
.PP
[workspaces] (label)
.RS 4
This tells fluxbox to insert a link to the workspaces menu directly into your menu\&. This is handy for those users who can\'t access the workspace menu directly (e\&.g\&. if you don\'t have a 3 button mouse, it is rather hard to middle click to show the workspace menu)\&.
.RE
.PP
[\fIcommand\fR] (label)
.RS 4
In addition to the commands above, any legal key command may be used as a menu item\&. See fluxbox\-keys(5) for more information\&.
.RE
.sp
Any line that starts with a \fI#\fR or \fI!\fR is considered a comment and ignored by fluxbox\&. Also, in the label/command/filename fields you can escape any character\&. Using \fI\e\e\fR inserts a literal back\-slash into the label/command/filename field\&.
.sp
Here is an example menu file:
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
# fluxbox menu file
[begin] (fluxbox)
    [exec] (rxvt) {rxvt \-ls} </usr/X11R6/share/icons/terminal\&.xpm>
    [exec] (netscape) {netscape \-install}
    [exec] (The GIMP) {gimp}
    [exec] (XV) {xv}
    [exec] (Vim) {rxvt \-geometry 132x60 \-name VIM \-e screen vim}
    [exec] (Mutt) {rxvt \-name mutt \-e mutt}
    [submenu] (mozilla)
        [exec] (browser) {mozilla \-browser}
        [exec] (news) {mozilla \-news}
        [exec] (mail) {mozilla \-mail}
        [exec] (edit) {mozilla \-edit}
        [exec] (compose) {mozilla \-compose}
    [end]
    [submenu] (Window Manager)
        [exec] (Edit Menus) {nedit ~/\&.fluxbox/menu}
        [submenu] (Style) {Which Style?}
            [stylesdir] (~/\&.fluxbox/styles)
            [stylesmenu] (fluxbox Styles) {@pkgdatadir@/styles}
        [end]
        [config] (Config Options)
        [reconfig] (Reconfigure)
        [restart] (Restart)
    [end]
    [exit] (Log Out)
[end]
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.SH "TOOLBAR"
.sp
The toolbar is a small area to display information like a clock, workspace name, a system tray or a taskbar (iconbar) that can contain the running programs\&. The color, look, font etc\&. is defined in the style and can\'t be defined as a global setting (except with the style overlay)\&.
.sp
The tools in the toolbar can be enabled/disabled in the init file with the arguments given to the line:
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
session\&.screen0\&.toolbar\&.tools
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.sp
The order and number of tools is freely selectable, but they must be separated by a ","\&. E\&.g\&.:
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
session\&.screen0\&.toolbar\&.tools: workspacename, systemtray, iconbar, clock
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.sp
The possible tools are:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBClock\fR: This will show an area to display a clock and the date according to the format specification listed in "man strtftime"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBIconbar\fR: This is the area that contains all windows (all running applications, all minimized windows or maybe no window, all depending on the Toolbar Settings)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBSystemtray\fR: The Systemtray can hold applications that are made to use it\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBWorkspaceName\fR: This displays the name of the current workspace\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBPrevWorkspace\fR: This displays an arrow that allows to switch to the workspace left of the current one\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBNextWorkspace\fR: This displays an arrow that allows to switch to the workspace right of the current one\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBPrevWindow\fR: This displays an arrow that switches focus to the previous visible window on the current workspace\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBNextWindow\fR: This displays an arrow that switches focus to the next visible window on the current workspace\&.
.RE
.sp
Other aspects of the toolbar can be configured in two ways: through the toolbar menu, which is accessable in the Configuration part of the RootMenu or with a right click on the edge the toolbar, or by editing the init file (see the RESOURCES section for more information about that)\&.
.SS "Configuration via the Toolbar Menu"
.sp
All changes take effect immediately, except for a change of the "Toolbar Alpha", which needs a restart to make the change visible\&. Here are the settings:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBVisible\fR: Sets the toolbar either to visible or invisible\&.
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
session\&.screen0\&.toolbar\&.visible: <boolean>
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBAuto hide\fR: If this is enabled the toolbar will disappear after a defined time when the mouse pointer leaves the toolbar\&. It will slide in when the cursor hits the remaining edge of the toolbar\&.
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
session\&.screen0\&.toolbar\&.autoHide: <boolean>
session\&.autoRaiseDelay: <int>
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBToolbar width percentage\fR: Sets the width of the toolbar in percent\&. Use the left mouse button to decrease and the right mouse\-button to increase the value\&. The value can be from 1\-100\&.
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
session\&.screen0\&.toolbar\&.widthPercent: <int>
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBMaximize Over\fR: Enabling this option will prevent windows from maximizing over the toolbar\&. With this switched on they will only expand to the edge of the bar\&. To use this option, "Full Maximization" from the Configuration menu must be DISABLED\&. Otherwise this option will not work\&.
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
session\&.screen0\&.toolbar\&.maxOver: <boolean>
session\&.screen0\&.fullMaximization: <boolean>
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBLayer\&...\fR: This sets the layer on which the toolbar is set\&. With this you can set the toolbar to "Always on top"\&.
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
session\&.screen0\&.toolbar\&.layer: <layer>
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBPlacement\fR: Sets the toolbar to any edge of the screen, either centered or aligned with a corner\&.
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
session\&.screen0\&.toolbar\&.placement: <direction>
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBAlpha\fR: This sets the alpha value for the toolbar\&. Use the left mouse button to decrease and the right mouse button to increase the value\&. 0 is invisible, 255 is not transparent at all\&.
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
session\&.screen0\&.toolbar\&.alpha: <int>
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBIconbar Mode\fR:
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
Specifies the mode of the iconbar:
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBNone\fR: will not show any windows
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBIcons\fR: shows windows from all workspaces that are minimized (iconified)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBNoIcons\fR: shows windows from all workspaces that are not minimized (iconified)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBWorkspaceIcons\fR: shows windows from the current workspace that are minimized (iconified)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBWorkspaceNoIcons\fR: shows windows from the current workspace that are not minimized (iconified)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBWorkspace\fR: shows all windows from the current workspace
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBAll Windows\fR: shows all windows from all workspaces
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
session\&.screen0\&.iconbar\&.mode: <mode>
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBAlignment\fR:
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBLeft\fR: all icons will be left\-aligned with the width set in the init file
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBRelative\fR: all icons will be sized evenly to fill the iconbar completely
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBRight\fR: all icons will be right\-aligned with the width set in the init file
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
session\&.screen0\&.iconbar\&.alignment: <alignment>
session\&.screen0\&.iconbar\&.iconWidth: <int>
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBShow Pictures\fR: If enabled the iconbar will show the application\'s icon (if provided by the application)
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
session\&.screen0\&.iconbar\&.usePixmap: <boolean>
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBClock\fR: Lets you switch between the 00:00am \- 11:59pm and 00:00 \- 23:59 notation
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBEdit Clock Format\fR: clicking this entry will pop up a little window in which the clock format can be set according to
\fIman strftime\fR
(or
\fIman date\fR)\&.
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
session\&.screen0\&.strftimeFormat: <format>
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.RE
.SH "RESOURCES"
.sp
Usually the ~/\&.fluxbox/init resource file is created and maintained by fluxbox itself\&. You can use the [config] menu to set most of these options\&. However, we\'ll cover all of the resource options that are available to the user\&. If you edit this file while fluxbox is running, you must `reconfigure\' to reload the resource options\&.
.sp
When running fluxbox in a multiple desktop environment the screen0 key can also be screen1, screen2, etc\&. You can customize the behavior of fluxbox on each desktop accordingly\&. Here are the resources that are currently available:
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
session\&.screen0\&.window\&.focus\&.alpha: <integer>
session\&.screen0\&.window\&.unfocus\&.alpha: <integer>
      These resources are available to the user to set different levels of
      transparency for different components of fluxbox\&. Each one accepts a value
      between 0\-255, 255 being opaque and 0 being completely transparent\&.
      Default: 255

session\&.screen0\&.slit\&.autoHide: <boolean>
session\&.screen0\&.toolbar\&.autoHide: <boolean>
      The autoHide resources allow the user to set the behavior of the toolbar
      and slit\&. This behavior can be that they disappear when they are not being
      used actively by the user, or they remain visible at all times\&. Default:
      False

session\&.screen0\&.slit\&.layer: <layer>
session\&.screen0\&.toolbar\&.layer: <layer>
      With these two resources, you can set the layer you want the toolbar and
      the slit to appear on\&. Please read the LAYER section for more information\&.
      Default: Dock

session\&.screen0\&.slit\&.placement: <placement>
session\&.screen0\&.toolbar\&.placement: <placement>
      These allow users to place the slit and toolbar where they like\&. Possible
      options are:
      \-   BottomLeft
      \-   BottomCenter
      \-   BottomRight
      \-   LeftBottom
      \-   LeftCenter
      \-   LeftTop
      \-   RightBottom
      \-   RightCenter
      \-   RightTop
      \-   TopLeft
      \-   TopCenter
      \-   TopRight

session\&.screen0\&.slit\&.maxOver: <boolean>
session\&.screen0\&.toolbar\&.maxOver: <boolean>
session\&.screen0\&.tabs\&.maxOver: <boolean>
      Setting these to True will allow application windows to maximize over the
      complete screen\&. Setting to False allows the slit, toolbar, and external
      tabs to hold their territory and will always be visible when an
      application is maximized\&. Default: False

session\&.screen0\&.toolbar\&.height: <integer>
      Set the height of the toolbar\&. If the value is set to 0, the style file
      will gain control over the toolbar height\&. It is possible to set a fixed
      height by changing this value to something greater than 0\&. Default: 0

session\&.screen0\&.toolbar\&.visible: <boolean>
      The user can set whether they want to have a toolbar on screen at all\&.
      Setting to False removes the toolbar from the screen\&. Default: True

session\&.screen0\&.toolbar\&.widthPercent: <integer>
      This resource sets the width percentage of the toolbar on the screen\&.
      Default: 65

session\&.screen0\&.toolbar\&.tools: <tools>
      This resource specifies the tools plugged into the toolbar\&. Read the
      TOOLBAR section in this manual for a description of each of these\&.
      Possible tools::
      \-   clock
      \-   iconbar
      \-   nextwindow
      \-   prevwindow
      \-   nextworkspace
      \-   prevworkspace
      \-   systemtray
      \-   workspacename

session\&.screen0\&.slit\&.onhead: <integer>
session\&.screen0\&.toolbar\&.onhead: <integer>
      For those that use xinerama, users can set this value to the number of the
      head where they would like to see the slit and toolbar, starting from 1\&.
      Setting this to 0 will ignore xinerama information\&. Default: 0

session\&.screen0\&.iconbar\&.mode: <pattern>
      This determines which windows will be displayed in the iconbar\&. Any window
      pattern available to the Next/PrevWindow keybindings is acceptable\&.
      Default: {static groups} (workspace)

session\&.screen0\&.iconbar\&.usePixmap: <boolean>
      This is also set in the Iconbar Mode menu\&. When set to True, this will
      show the native icon of applications\&. Default: True

session\&.screen0\&.iconbar\&.iconTextPadding: <integer>
      This specifies the space between the window title and the edge of the
      button\&. Default: 10

session\&.screen0\&.iconbar\&.alignment: <position>
      This value should be changed in the Iconbar Mode menu\&.  Default:
      Relative

      Available options:
      \-   Left: Fixed width, aligned left
      \-   Relative: Width varies to fill the iconbar
      \-   Right: Fixed width, aligned right

session\&.screen0\&.iconbar\&.iconWidth: <integer>
      Used to specify the iconbar button width for Left/Right alignment\&.
      Default: 70

session\&.screen0\&.strftimeFormat: <date>
      This adjusts the way the current time is displayed in the toolbar\&. The
      strftime(3) format is used\&. Default: %I:%M %p

session\&.screen0\&.tabs\&.intitlebar: <boolean>
      This specifies whether tabs should be embedded in the titlebar or placed
      outside the window\&. Default: True

session\&.screen0\&.tab\&.placement: <placement>
      This specifies where external tabs will appear on the window\&. Default:
      TopLeft

session\&.screen0\&.tab\&.width: <integer>
      This specifies the width of external tabs in pixels\&. Default: 64

session\&.screen0\&.focusModel: ClickToFocus|MouseFocus
      This controls how windows gain focus via the mouse\&. With `ClickToFocus\',
      the user must click on the window\&. With `MouseFocus\', windows gain focus
      whenever the mouse moves over them\&. Default: ClickToFocus

session\&.screen0\&.autoRaise: <boolean>
      When True, this setting automatically raises any window that gains focus\&.
      Default: True

session\&.autoRaiseDelay: <integer>
      Adjusts the delay (in milli\-sec) before focused windows will raise
      when using the Autoraise option\&. Default: 250

session\&.screen0\&.clickRaises: <boolean>
      This setting allows a user to click anywhere on a window to bring it on
      top of other windows\&. Otherwise, only the titlebar will work\&. Default:
      True

session\&.screen0\&.workspacewarping: <boolean>
      This setting enables a user to change workspaces by dragging a window
      across the edge of the screen\&. Default: True

session\&.screen0\&.showwindowposition: <boolean>
      Setting this resource to True shows the user, in a little window,
      the exact position of the application window while the user is
      dragging it\&. Allows a precise placement of windows on a screen\&.
      Default: True

session\&.screen0\&.defaultDeco: <string>
      This specifies the default window decorations, according to the same
      options available to the `[Deco]\' option in the `apps\' file, described in
      the APPLICATIONS section\&. Default: NORMAL\&.

session\&.screen0\&.menuMode: Delay|Click
      This setting controls the circumstances under which submenus open\&. With
      `Click\', the user must click on the menu item in order for the submenu to
      open\&. With `Delay\', submenus open when the mouse hovers over the menu
      item\&. Default: Delay

session\&.screen0\&.menuDelay: <integer>
      This sets the delay in milliseconds for submenus to open with the previous
      option set to `Delay\'\&. Default: 0

session\&.screen0\&.menuDelayClose: 0
      This value sets the delay in milliseconds that you would like the menu to
      remain visible after you\'ve clicked out of it\&. Default: 0

session\&.screen0\&.focusNewWindows: <boolean>
      This sets whether or not new windows will become focused automatically\&.
      Default: True

session\&.screen0\&.workspaceNames: <names>
      Here is where the user can name their workspaces\&. However it is
      recommended to use the tool available in the Configuration Menu to set
      these\&. Default: one, two, three, four

session\&.screen0\&.edgeSnapThreshold: <integer>
      When moving a window across your screen, fluxbox is able to have it `snap\'
      to the edges of the screen and other windows for easy placement\&. This
      variable tells fluxbox the distance (in pixels) at which the window will
      jump to the edge\&. Default: 10

session\&.screen0\&.windowPlacement: <placement strategy>
      This resource specifies where to place new windows when not otherwise
      specified (by the program or the `apps\' file, for example)\&. Here are the
      options:
      \- RowSmartPlacement: tries to place windows in rows without overlapping
      \- ColSmartPlacement: tries to place windows in columns without overlapping
      \- CascadePlacement: places windows below the titlebar of the previous one
      \- UnderMousePlacement: places new windows underneath the mouse
      Default: RowSmartPlacement

session\&.screen0\&.rowPlacementDirection: LeftToRight|RightToLeft
session\&.screen0\&.colPlacementDirection: TopToBottom|BottomToTop
      These settings control the direction in which windows are tiled using the
      RowSmartPlacement and ColSmartPlacement strategies described above\&.
      Default: LeftToRight/TopToBottom

session\&.screen0\&.fullMaximization: <boolean>
      If this setting is enabled, windows will maximize over the toolbar, slit,
      and any other window that creates a strut, no matter what their individual
      settings are\&. Default: False

session\&.screen0\&.opaqueMove: <boolean>
      When moving a window, setting this to True will draw the window
      contents as it moves (this is nasty on slow systems)\&. If False, it
      will only draw an outline of the window border\&. Default: True

session\&.screen0\&.workspaces: <integer>
      Set this to the number of workspaces the users wants\&. Default: 4

session\&.screen0\&.windowMenu: <blank>|<location>
      This specifies the location of a user\-defined window menu\&. Default: blank

session\&.appsFile: <location>
session\&.groupFile: <location>
session\&.keyFile: <location>
session\&.menuFile: <location>
session\&.slitlistFile: <location>
session\&.styleFile: <location>
session\&.styleOverlay: <location>
      All of these resources require a pathname to their specific files\&. This is
      where you can specify different files\&. Most of the defaults will be
      located in the user\'s ~/\&.fluxbox directory\&.

session\&.cacheLife: <integer>
      This tells fluxbox how long (in minutes) unused pixmaps may stay in the X
      server\'s memory\&. Default: 5

session\&.cacheMax: <integer>
      This tells fluxbox how much memory (in Kb) it may use to store cached
      pixmaps on the X server\&. If your machine runs short of memory, you may
      lower this value\&. Default: 200

session\&.colorsPerChannel: <integer>
      This tells fluxbox how many colors to take from the X server on
      pseudo\-color displays\&. A channel would be red, green, or blue\&. fluxbox
      will allocate this variable ^ 3 and make them always available\&. Value must
      be between 2\-6\&. When you run fluxbox on an 8bpp display, you must set this
      resource to 4\&. Default: 4

session\&.doubleClickInterval: <integer>
      Adjust the delay in milliseconds between mouse clicks for fluxbox to
      consider a double click\&. Default: 250

session\&.forcePseudoTransparency: <boolean>
      If you have Xorg\'s composite extension enabled, this setting will force
      the menu, windows, toolbar, and slit to use pseudo\-transparency instead of
      true transparency\&. Default: False

session\&.ignoreBorder: <boolean>
      This configures the ability to move windows by dragging the border\&.
      Default: False

session\&.tabPadding: <integer>
      This specifies the spacing between tabs\&. Default: 0

session\&.tabsAttachArea: Window|Titlebar
      With this set to `Window\', windows may be grouped by dragging one tab with
      the middle mouse button and dropping it anywhere on another window\&. With
      `Titlebar\', the user must drop the tab on the target window\'s titlebar\&.
      Default: Window

session\&.titlebar\&.left: Stick
session\&.titlebar\&.right: Minimize Maximize Close
      The icons to place in the titlebar of decorated windows\&. The available
      options are Close, Maximize, MenuIcon, Minimize, Shade, and Stick\&.
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.SH "KEYS"
.sp
You can customize fluxbox\'s key handling through the ~/\&.fluxbox/keys file\&. See \fIfluxbox\-keys(5)\fR for more information on the syntax of this file\&.
.SH "LAYERS"
.sp
Layers affect the way that windows will overlap each other on the screen\&. Windows on a higher layer will always appear above those on a lower one, whether they are focused or not\&. By default, fluxbox uses 13 layers, starting from 1 (highest)\&. The number of layers can be changed by using the following resource:
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
session\&.numLayers: <integer>
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.sp
There are two ways to assign a window to a different layer\&. When the window is open, you may select the layer in the `Layer \&...\' submenu of the window menu\&. The menu gives six choices for the layer, which fluxbox manages by name\&. The names are (from highest to lowest layer):
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
2 \- Above Dock
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
4 \- Dock
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
6 \- Top
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
8 \- Normal
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
10 \- Bottom
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
12 \- Desktop
.RE
.sp
The other way to set the layer for a window is through the `apps\' file\&. This method is described in the APPLICATIONS section\&.
.SH "FOCUS MODEL"
.sp
The Focus Model defines how windows gain focus (i\&.e\&. become the active window, which receives keyboard and mouse events)\&. The focus model can be changed in the configuration menu (usually located under \fIfluxbox menu\fR in the Root Menu\&.
.sp
There are two main aspects of the focus model: how windows gain focus and how tabs gain focus\&. Each of these has two options: focus follows mouse and click to focus\&. Focus follows mouse means that windows will gain focus when the mouse hovers over them\&. Click to focus means that windows will gain focus when the mouse clicks on them\&.
.sp
Thus, there are four main options when choosing a focus model\&. You should choose one of the first two and one of the last two\&. They are:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBClick To Focus\fR: click to focus windows
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBMouse Focus\fR: window focus follows mouse
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBClickTabFocus\fR: click to focus tabs
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBMouseTabFocus\fR: tab focus follows mouse
.RE
.sp
There is one more option in the focus model menu\&. It is called AutoRaise\&. When AutoRaise is enabled, focused windows will appear on top of other windows in the same layer\&. When AutoRaise is disabled, you must explicitly raise a focused window, using the window menu or keybinding\&.
.SH "TAB OPTIONS"
.sp
This section of fluxbox configuration menu lets you configure many features of tabs\&. Inside of it there are three main options:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBPlacement\fR: You can choose where the external tabs will be positioned relative to the window\&. For these options to work,
\fITabs in Titlebar\fR
must be off\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBTabs in Titlebar\fR: When this option is on, tabs are fixed in window titlebar and the width varies according to the amount of windows grouped\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBMaximize Over\fR: When this option is on, maximizing a window will disregard the size and location of external tabs\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBExternal Tab Width\fR: This specifies in pixels the width of external tabs\&.
.RE
.sp
As with most Fluxbox configurations, these options can be changed by editing the init file\&. The resources that you should look at are:
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
session\&.screen0\&.tabs\&.intitlebar: <boolean>
session\&.screen0\&.tab\&.width: <integer>
session\&.screen0\&.tab\&.placement: <direction>
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.SH "STYLES"
.sp
fluxbox enables you to use specialized files that contain X(1) resources to specify colors, textures, pixmaps and fonts, and thus the overall look of your window borders, menus and the toolbar\&.
.sp
The default installation of fluxbox provides some of these style files\&. See fluxstyle(1) to accommodate the growing number of style components\&.
.SH "STYLE OVERLAY"
.sp
In addition to the style file, the overlay file, whose location is specified by session\&.screen0\&.styleOverlay (default: ~/\&.fluxbox/overlay ) can be used to set style resources that override all styles\&. For more information about which parts of fluxbox can be controlled by the overlay file, see fluxstyle(1)\&.
.SH "APPLICATIONS"
.sp
It is possible to force an application to always have the same dimensions, position, and other settings when it is first launched\&. The easiest way to do this is to use the `Remember\&...\' submenu of the window menu, which can usually be opened with a right click on the titlebar\&. More advanced features require manually editing the ~/\&.fluxbox/apps file, where these settings are saved\&.
.sp
The format of a section in the `apps\' file is:
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
[app] (Property=\'value\') \&.\&.\&. {count \- optional}
    [Setting1]  {value1}
    [Setting2]  {value2}
    \&.\&.\&.
[end]
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.sp
Property can be one of the following tags:
.sp
o name \- the name of the window (the first field of WM_CLASS) o class \- class of the window (the second field of WM_CLASS) o title \- title of the window (the WM_NAME property) o role \- role of the window (the WM_WINDOW_ROLE property)
.sp
You can find out the value for these fields for a particular window by running xprop(1)\&. The window title should be used only as a last resort, since it often changes after the window opens\&. Each \fIvalue\fR can be a string or a regular expression\&. All values are case sensitive\&.
.sp
You can specify multiple properties, which must ALL match for the settings to be applied\&. If a count is supplied in curly brackets at the end of the app line, then the entry will only match at most that many at any time (default is to match all matching windows)\&. Settings associated with an [app] line will not be applied to transient windows\&. [transient] may be used instead to match them\&.
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
# match a standard xterm
[app] (name=xterm)
# match an xterm started like: xterm \-name myshell
[app] (name=myshell)
# match the gaim buddy list window
[app] (role=buddy_list)
# match an rdesktop window to a particular host
[app] (title=rdesktop \- hostname\&.*)
# match pidgin IRC windows
[app] (pidgin) (title=#\&.*)
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.sp
The following are the settings that can be defined in each [app] entry\&. Each name must be enclosed in square brackets, and the value is generally in curly brackets:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[Workspace] {0\-N}: Forces the application to open on the workspace specified\&. Workspaces are set by number, beginning with 0\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[Dimensions] {Width Height}: Open the application with the specified width and height, in pixels\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[Position] (\fBrefspot\fR) {X Y}: Position the application at a particular spot:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
TOPLEFT
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
TOP
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
TOPRIGHT
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
LEFT
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
CENTER
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
RIGHT
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
BOTTOMLEFT
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
BOTTOM
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
BOTTOMRIGHT
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
You can optionally specify what X and Y are relative to\&. By default the
upper left corner is placed at screen coordinates (X, Y)\&. If you specify a
reference point, say LOWERRIGHT, then the lower right corner of the window
is positioned (X,Y) pixels from the lower right of the screen\&.
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Specify the layer to open the window on (by number)\&. Each layer has a number\&. The named ones are: 2\-AboveDock, 4\-Dock, 6\-Top, 8\-Normal, 10\-Bottom, 12\-Desktop\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[Shaded] {yes|no}: The window is started shaded, or not\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[Tab] {yes|no}: Whether this window can be tabbed with others\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[IconHidden] {yes|no}: Hides the app from the icon bar
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[FocusHidden] {yes|no}: Hides the app from the window cycling list used by Next/PrevWindow key bindings\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[Hidden] {yes|no}: is both [IconHidden] plus [FocusHidden]
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[Deco] {NONE|NORMAL|TOOL|TINY|BORDER}: Specify the decoration state\&. There are several predefined dec\- oration sets:
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
o   NORMAL \- standard decorations
o   NONE \- no decorations
o   BORDER \- like NONE except keep the X window border
o   TINY \- titlebar with an iconify button
o   TOOL \- titlebar only
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
A bitmask can also be used for fine\-grained control\&.  The bits are (from
"1" to 1<<10): titlebar, handle/grips, border, iconify button, maximize
button, close button, menu enabled, sticky button, shade button, tabbing
enabled, focus enabled\&.
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[Sticky] {yes|no}: Whether the window is initially stuck or not\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[Jump] {yes|no}: Jump to workspace\&. This one is only useful if `Workspace\' is set too\&. The workspace is changed to the workspace containing the application being launched\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[Close] {yes|no}: Save settings on close\&. By default, application settings are not saved when a window is closed\&. Set this option if you want previous settings to be saved when the window is closed\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[Alpha] {int [int]} Where numbers represent focused and unfocused transparency, respectively\&. One number only will be used for both\&.
.RE
.sp
The apps file also allows you to specify applications that should be started only valid option is (screen=NN), where NN is the screen number on which the command should be run\&.
.sp
Finally, you can set windows to group together by using the `apps\' file\&. Just place a [group] tag around several [app] tags, with an [end] tag to indicate the end of the group\&. If you place (workspace) after the [group] tag, a new window will only get grouped with other windows on the current workspace\&. You can also specify dimensions, positions, etc\&. for the group as for normal app entries\&. Here is a short example of an `apps\' file:
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
    [startup] {xterm}
    # match anything ending with term, up to 2 instances
    [app] (name=\&.*[tT]erm) {2}
      [Workspace]   {1}
    [end]
    [app] (name=kate)
      [Dimensions]  {1022 747}
      [Position]    (WINCENTER) {0 0}
      [Close]       {yes}
    [end]
    [app] (name=konqueror)
      [Workspace]   {1}
      [Dimensions]  {1006 749}
      [Position]    {16 0}
      [Jump]        {yes}
    [end]
    # start all aterms without decorations
    [app] (name=aterm)
      [Deco]        {NONE}
    [end]
    # a group with the gimp dock and toolbox
    # appears on layer 4 (bottom)
    [group]
     [app] (name=gimp) (role=gimp\-dock)
     [app] (name=gimp) (role=gimp\-toolbox)
      [Layer]       {4}
    [end]
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.SH "THE SLIT"
.sp
The slit is a special fluxbox window frame that can contain dockable applications, e\&.g\&. \fIbbtools\fR or \fIwmapps\fR\&.
.sp
When applications are run in the slit they have no window borders of their own; instead they are framed in the slit, and they are always visible in the current workspace\&.
.sp
Most dockable applications use the \-w option to run in the slit\&. For example, you could put in your ~/\&.xinitrc:
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
bbmail \-w &
bbpager \-w &
wmdrawer &
exec fluxbox
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.sp
NOTE: You can also put all of these in the startfluxbox(8) script\&. This way you would only need to specify: exec startfluxbox in your ~/\&.xinitrc\&.
.sp
To use the slit you must have it compiled into fluxbox\&. This is the default setting\&.
.SH "Slit Menu"
.sp
You can right click on the edge of the slit window to get a menu to configure its position, whether its contained applications should be grouped horizontally or vertically and whether the slit should hide itself when the mouse moves away\&. The slit menu items are described in more detail below:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBPlacement\fR: This lets you set the position of the slit\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBLayer\fR: Look above for the layer priorities\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBAuto hide\fR: If enabled, the slit will disappear after a given amount of time and hide from the view of the user\&. You can make it appear if you move the mouse to the edge of the desktop where the slit is positioned\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBMaximize over\fR: If this is enabled, all windows, if you maximize them, will stretch over/under the slit\&. Otherwise the will be limited to the slit\'s edge\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBAlpha\fR: By changing the value the slit (only the decoration not the apps in the slit) will become transparent\&. 0 (transparent) \- 255 (opaque)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBClients\fR: This submenu lets you reorder the the applications running in the slit\&. You are able to hide apps from the slit by unselecting them in the list showing\&. This will not kill the app\&. You can make them appear by selecting them in the list\&. The "Save SlitList" option saves the new order to you slitlist located in ~/\&.fluxbox (useful if you reordered the apps with the cycle option)\&.
.RE
.SH "Slitlist File"
.sp
fluxbox\'s slitlist file is available for those that use dockapps in the slit\&. This file helps fluxbox keep track of the \fBorder\fR of the dockapps when in the slit\&. The file is generally located at ~/\&.fluxbox/slitlist
.sp
A simple procedure for getting the slit sequences the way you like it is: 1\&. Run fluxbox with no pre\-loaded dockapps 2\&. Run dockapps individually in the order you want them 3\&. Add dockapps to your auto\-run script, or better yet your startfluxbox(8) script\&.
.sp
This sequence will be saved by default to ~/\&.fluxbox/slitlist and will be remembered for future instances of fluxbox\&.
.sp
Users are free to manually edit the slitlist file\&. It is a simple list of window names, as given by xprop(1), one per dockapp\&. Similar to the init file it should not be edited while fluxbox is running\&. Otherwise changes may get overwritten\&.
.sp
The user also has the option of choosing a different path for the slitlist file\&. The following is the init file component that needs to be changed:
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
session\&.session0\&.slitlistFile: <filename>
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.SH "ENVIRONMENT"
.PP
HOME
.RS 4
fluxbox uses HOME to find the \&.fluxbox/init file and to resolve style file and \-directory names\&.
.RE
.PP
DISPLAY
.RS 4
When no other display was given on the command line, fluxbox will start on the display specified by this variable\&.
.RE
.sp
fluxbox can also take advantage of other environment variables if they are set before fluxbox is started\&. For example, if $TERM is set, then it will be available whenever fluxbox uses the shell, such as certain commands in the keys and menu files\&. So one can do:
.sp
.if n \{\
.RS 4
.\}
.fam C
.ps -1
.nf
.BB lightgray
Mod1 x ExecCommand :$TERM
.EB lightgray
.fi
.fam
.ps +1
.if n \{\
.RE
.\}
.sp
For more information about environment variables, see your shell\'s manual\&.
.SH "SIGNALS"
.sp
fluxbox responds to the following signals:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
SIGHUP fluxbox loads the configuration\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
SIGUSR1 Forces reloading of configuration\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
SIGUSR2 Forces reloading of menu file\&.
.RE
.SH "AUTHOR and CREDITS"
.sp
fluxbox is written and maintained by Henrik Kinnunen <fluxgen at fluxbox org>, Simon Bowden <rathnor at fluxbox org>, Mathias Gumz <akira at fluxbox org>, and Mark Tiefenbruck <mark at fluxbox org>, with contributions and patches merged from many individuals around the world\&.
.sp
Blackbox was written and maintained by Brad Hughes <blackbox at alug org> and Jeff Raven <jraven at psu edu>\&.
.sp
The Official fluxbox website: http://www\&.fluxbox\&.org
.sp
Many compatible themes: \- http://boxwhore\&.org \- http://themes\&.freshmeat\&.net/
.sp
This manpage is the combined work of:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Curt Micol <asenchi at asenchi com> (>fluxbox\-0\&.9\&.11)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Tobias Klausmann <klausman at users sourceforge net> (\(lafluxbox\-0\&.9\&.11)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Grubert <grubert at users sourceforge net> (fluxbox)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Matthew Hawkins <matt at mh dropbear id au> (blackbox)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Wilbert Berendsen <wbsoft at xs4all nl> (blackbox)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Numerous other languages could be available if someone jumps in\&.
.RE
.SH "BUGS"
.sp
If you find any bugs, please visit the #fluxbox irc channel on irc\&.freenode\&.net or submit them to the bug tracker at http://sf\&.net/projects/fluxbox \&. Or you may subscribe to one of the mailinglists\&. More information can be found on the official website\&.
.SH "SEE ALSO"
.sp
fluxbox\-keys(5) bsetroot(1) fbsetbg(1) fbrun(1) fluxstyle(1)
