.\"     Title: fluxbox
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 08/20/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "FLUXBOX" "1" "08/20/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
fluxbox - Ein schneller, hochkonfigurierbarer Fenstermanager fuer X11
.SH "SYNOPSIS"
\fIfluxbox\fR [\-v | \-version] [\-h | \-help] [\-i | \-info]
.sp
\fIfluxbox\fR [\-rc rcfile] [\-log logfile] [\-display display] [\-screen scr,scr|all] [\-verbose]
.sp
.SH "BESCHREIBUNG"
fluxbox(1) stellt unter anderem konfigurierbare Fensterverzierungen, ein Menue zum starten von Anwendungen sowie eine Toolbar, welche den Namen der aktuellen Arbeitsflaeche, ausgewaehlte Fenster und die aktuelle Uhrzeit anzeigt\. Ueber ein Arbeitsflaechenmenue koennen Arbeitsflaechen hinzugefuegt, entfernt oder umbenannt werden\. Der Slit ermoeglicht kleine Anwendungen anzudocken, als Beispiel seien die bbtools oder Dockapps genannt\.
.sp
fluxbox(1) kann Fenster in die Toolbar minimieren und zusaetzlich ins \fIIcons\fR Untermenue des Arbeitsflaechenmenues hinzufuegen\. Ein einziger Klick und die Fenster sind wieder da\. Ein Doppelklick auf den Fenstertitel und das Fenster wird auf/abgerollt, will heissen: nur noch der Fenstertitel ist sichtbar\.
.sp
fluxbox(1) verwendet eine eigene Graphikklasse um die benoetigten Graphiken darzustellen\. Mit Farbschemadateien kann der Nutzer den Desktop bis ins Detail persoenlich gestalten\. Farbschemata von Blackbox 0\.65 (oder aelter) koennen in fluxbox verwendet werden, so dass bei einer Umstellung von blackbox das Aussehen genau gleich bleibt\.
.sp
fluxbox(1) unterstuetzt weitgehend die EWMH Spezifikationen sowie andere Standards der Fensterverwaltung\. Das ermoeglicht eine einheitliche Ansteuerung aller Fenstermanager und vereinfacht die Interoperabilitaet zwischen verschiedenen Anwendungen, Werkzeugen und Desktops\.
.sp
.SH "OPTIONS"
.PP
\-display display
.RS 4
Startet fluxbox auf der angegebenen Anzeige\. Von fluxbox gestartete Anwendungen uebernehmen diese Einstellung
.RE
.PP
\-h, \-help
.RS 4
Zeigt eine Kurzhilfe mit den typischen Optionen an
.RE
.PP
\-i, \-info
.RS 4
Zeigt wichtige Informationen wie die Version sowie einkompilierte Funktionen an
.RE
.PP
\-log logfile
.RS 4
fluxbox wird das angegebene Logfile benutzen
.RE
.PP
\-rc rcfile
.RS 4
fluxbox verwendet eine andere Konfigurationsdatei als ~/\.fluxbox/init
.RE
.PP
\-v, \-version
.RS 4
Zeigt die Versionsnummer an
.RE
.PP
\-screen scr,scr|all
.RS 4
fluxbox wird auf den angegebenen screens ausgefuehrt
.RE
.PP
\-verbose
.RS 4
fluxbox gibt waehrend der Laufzeit zusaetzliche Informationen aus
.RE
.SH "FLUXBOX STARTEN"
fluxbox(1) bringt ein weiteres Programm namens startfluxbox(8) mit, welches sich ueblicherweise in dem selben Verzeichnis befindet wie fluxbox selber\. Dieses Skript ermoeglicht es, zusaetzliche Variablen und Optionen anzupassen\. fluxbox sollte ueber startfluxbox gestartet werden, ergo kann man "exec startfluxbox" in der /\.xinitrc oder /\.xsession (je nach verwendeter Distribution oder verwendetem Desktopmanager) als letzten Befehl eintragen\. Dabei muss sich startfluxbox und fluxbox in $PATH befindet, was ueblicherweise der Fall ist\.
.sp
fluxbox \-i zeigt die von fluxbox(1) verwendeten Standarddateien und Optionen an\. Diese Dateien koennen fuer Systemweite Einstellungen / Menues verwendet werden, die dann fuer alle Anwender gelten\.
.sp
Beim Beenden oder Neustarten speichert fluxbox die Anwendereinstellungen in der Datei ~/\.fluxbox/init Die Einstellungen koennen von Hand mit einem Texteditor oder ueber die verschiedenen fluxboxmenues konfiguriert werden\.
.sp
.SH "FLUXBOX BENUTZEN"
Viele Nutzer, die sich eine Desktopumgebung wie Gnome oder KDE gewohnt sind, sind beim ersten Start von fluxbox ein wenig ueberrascht, da sich fast nichts auf dem Bildschirm befindet\. fluxbox ist auf auf Schnelligkeit und Konfigurierbarkeit getrimmt, ergo wird man sicher ein wenig Zeit brauchen um sich umzugewoehnen\. Viele finden aber, dass sich der einmalige Zeitaufwand durchaus lohnt\.
.sp
Es folgt nun eine Kurzuebersicht ueber die allgemeinen Dinge in fluxbox\. Wir empfehlen allerdings, dass man die entsprechenden Abschnitte in dieser Anleitung liest um sich mit den Details vertraut zu machen\.
.sp
.SS "Root Window (Main)"
Beim ersten Start von fluxbox sieht man lediglich die Toolbar\. Ein Rechtsklick (dritter Mausknopf) auf den leeren Desktop bringt das RootMenue hervor\. Ein Klick auf den mittleren Mausknopf (zweiter Mausknopf, meist das Mausrad) bringt das Arbeitsflaechenmenue hervor\.
.sp
.SS "RootMenue und das Arbeitsflaechenmenue"
Ueber das RootMenue kann man Anwendungen starten und fluxbox konfigurieren\. Das Arbeitsflaechenmenue zeigt alle Fenster auf den einzelnen Arbeitsflaechen\. Im Abschnitt MENUES steht wie die beiden Menues angepasst werden koennen\.
.sp
.SS "Toolbar"
Der Inhalt der Toolbar kann in der init Datei konfiguriert werden\. Diese Datei wird im Abschnitt RESSOURCEN genau beschrieben\. In der Toolbar befindet sich eine Kombination aus folgenden Werkzeugen:
.sp
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBWorkspace Name\fR: Der Name der aktuellen Arbeitsflaeche
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBIconbar\fR: Eine Liste der von fluxbox verwalteten Fenster
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBSystem Tray\fR: Systemabschnitt fuer Applets
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBClock\fR: Uhrzeit und Datum (standardmaessig nur Uhrzeit)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBWorkspace Arrows\fR: Vorige/Naechste Arbeitsflaeche
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBWindow Arrows\fR: Voriges/Naechstes Fenster (fokussieren)
.RE
.SS "Slit"
Der Slit wird von vielen nicht wahrgenommen, weil man ihn nicht sehen kann solange er nicht Benutzt wird\. Der Slit ist ein Ort an dem sich kleine Programme andocken koennen\. Applikationen wie gkrellm oder fbpager koennen anstelle von Fenstern gedockte Applikationen sein\. Dem Slit ist in dieser Anleitung weiter unten ein ganzer Abschnitt gewidmet\.
.sp
.SS "Ebenen"
Fenster auf einer hoeheren Ebene werden automatisch oberhalb von denen auf tieferen Ebenen platziert, unabhaengig vom Fokus\. Nebst den Fenstern koennen auch der Slit und die Toolbar auf eine Ebene gelegt werden\. Anwendungen koennen mit Hilfe der `apps\' Datei oder ueber das Fenstermenue einer Ebene zugewiesen werden\. Mehr ueber die `apps\' Datei steht im ANWENDUNGEN Abschnitt, mehr ueber das Fenstermenue im Abschnitt MENU\. Die Ebenen werden im gleichnamigen Abschnitt genauer behandelt\. fluxbox platziert Fenster auf folgenden Ebenen: (von oben nach unten)
.sp
.sp
.RS 4
\h'-04'\(bu\h'+03'ueberDock
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Dock
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Oben
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Normal
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Unten
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Desktop
.RE
.SS "Fokustyp"
Maus\- und Tastatureingaben werden jeweils an das Fenster mit Fokus weitergegeben (Globale Tastenkuerzel ausgenommen)\. Ueber das fluxboxmenue kann das Fokusverhalten festgelegt werden\. Im Abschnitt FOKUS sind die verschiedenen Modelle genauer beschrieben\.
.sp
.SS "Fenster"
Ein Linksklick auf einen beliebigen Teil des Fensterrahmens bringt das Fenster in den Vordergrund\. Wird die Maus dabei bewegt kann das Fenster verschoben werden\. ueber die unteren Ecken kann das Fenster so auch vergroessert oder verkleinert werden\. Ein Klick mit der mittleren Maustaste legt das Fenster unter alle anderen\. Ein Rechtsklick auf den Fenstertitel blendet das Fenstermenue ein, welches im Abschnitt MENU genauer beschrieben wird\.
.sp
.SS "Reiter (Tabs)"
fluxbox ermoeglicht es Fenster zu gruppieren, indem man ein Fenster mit der mittleren Maustaste packt und in ein anderes zieht\. Dieses tabben ermoeglicht es mehrere Anwendungen an einem zentralen Ort zu haben und gleichzeitig zu verschieben/vergroessern/verkleinern\. Standardmaessig werden die Reiter ausserhalb des Fensters angezeigt, sie koennen allerdings auch in den Fenstertitel eingebettet werden\. Die Konfiguration der Reiter wird im Abschnitt REITEROPTIONEN erlaeutert\.
.sp
.SH "MENU"
fluxbox installiert eine Standard\-Menuedatei unter @pkgdatadir/menu\. Beim Aufruf von fluxbox \-i wird diese mit Pfad angezeigt\. Dieses Systemweite Menue gilt fuer alle Nutzer\. Es ist natuerlich moeglich, dass jeder Nutzer seine eigene Menuedatei hat\. Diese liegt normalerweise unter ~/\.fluxbox/menu\. In der ~/\.fluxbox/init Datei wird angegeben welche Menuedatei fluxbox verwenden soll\. Die Option dazu ist:
.sp
.sp
.RS 4
.nf
session\.menuFile: <menufile>
.fi
.RE
Um eine Aenderung daran wirksam werden zu lassen, muss fluxbox neu gestartet werden\. Vorher sollte man sicherstellen, dass die Menuedatei korrekt ist und von fluxbox verwendet werden kann\. Aenderungen in der Menuedatei selber erfordern keinen Neustart, sie werden von fluxbox sofort uebernommen\.
.sp
In saemtlichen Menues hat man die Moeglichkeiten von typeahead, will heissen man kann Eintraege auch durch schreiben der ersten paar Buchstaben auswaehlen\. Der aktuelle Eintrag wird dabei jeweils von fluxbox unterstrichen\. Die Tabulator\-Taste oeffnet ein Untermenue wenn die Zeichenfolge einmalig ist, backspace schliesst, wenn nichts getippt wurde, das aktuell geoeffnete Menue\.
.sp
.SS "Root Menu"
Das Rootmenue wird unter anderem verwendet, um fluxbox zu konfigurieren\. Die meisten Konfigurationen koennen auch von Hand in der `init\' Datei durchgefuehrt werden\. Allerdings ist die Verwendung des Rootmenues meist schneller als einen Texteditor zu nutzen und die entsprechende Einstellung zu suchen\. Es folgen die wichtigsten Menuepunkte:
.sp
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBConfigure\fR: In dem Untermenue koennen die meisten Einstellungen bezueglich dem Verhalten von fluxbox und den Werkzeugen vorgenommen werden\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBSystem Styles\fR: Hier werden die Systemweiten Farbschemata gelistet\. Ein einfaches Auswaehlen per Mausklick reicht, allerdings muss je nach dem welche Elemente von den Stilaenderungen betroffen sind fluxbox neu gestartet werden\. Die Farbschemata befinden sich unter @pkgdatadir@/styles/ bei einer Standardinstallation\. Mit fluxbox \-i kann man das ueberpruefen\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBUser Styles\fR: Die Farbschemata, die sich unter ~/\.fluxbox/styles befinden werden hier aufgelistet\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBWorkspace List\fR: Listet die eingerichteten Arbeitsflaechen und die sich darauf befindenden Fenster auf
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBTools\fR: Diverse kleine Werkzeuge die von fluxbox mitgeliefert werden, zum Beispiel um eine Arbeitsflaeche umzubenennen\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBWindow\fR: Kann verwendet werden um zu einem anderen Fenstermanager oder einer Desktopumgebung umzuschalten\. fluxbox wird dabei beendet, die Fenster aber nicht geschlossen\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBLock Screen\fR: Sperrt den Bildschirm
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBfluxbox Command\fR: Ein kleiner Dialog um einen Befehl auszufuehren
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBReload Config\fR: Liest die Konfigurationsdateien neu ein
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBRestart\fR: Startet fluxbox neu\. Saemtliche Konfigurationsdateien werden neu eingelesen, alle graphischen Elemente neu gezeichnet\. Die Anwendungen werden dabei nicht geschlossen\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBExit\fR: Beendet fluxbox und den X Server
.RE
.SS "Konfigurationsmenue"
Hier kann fluxbox konfiguriert werden\. Die Verwendung dieses Menues ist meist schneller als das editieren der init Datei und sollte von daher bevorzugt werden\. Zudem entfaellt so die Moeglichkeit eines Tippfehlers\. Die Bezeichnungen sind: Deutsche uebersetzung / Original
.sp
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBFokustyp / Focus Model\fR: Mehr dazu unter FOKUSTYP am Ende dieser Anleitung
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBTab\-Einstellungen / Tab Options\fR: Ermoeglicht die Konfiguration der Reiter (Tabs)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBSlit / Slit\fR: Damit kann der Slit konfiguriert werden\. Mehr dazu steht im Abschnitt SLIT
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBToolbar / Toolbar\fR: Alles dazu steht im Abschnitt TOOLBAR, unter Toolbar ueber das Menue konfigurieren\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBBilddithering / image dithering\fR: Bilddithering aktivieren/deaktvieren
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBFensterinhalt beim Verschieben anzeigen / Opaque Window Moving\fR: Falls eingeschaltet, wird beim Verschieben von Fenstern deren Inhalt angezeigt, ansonsten nur der Fensterrahmen\. Vor allem bei langsamen Rechnern nuetzlich\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBVollstaendig maximieren / Full Maximization\fR: Maximiert Fenster auf volle Bildschirmgroesse, auch wenn sie dabei unter/ueber den Slit oder die Toolbar geraten\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBNeue Fenster fokussieren / Focus New Window\fR: Wenn diese Option aktiviert ist bekommt ein neu erstelltes Fenster automatisch den Fokus\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBFenster ueber Desktopgrenzen verschieben / Windows Warping\fR: Ermoeglicht es Fenster ueber mehrere Arbeitsflaechen zu verschieben\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBDesktop mit Mausrad wechseln / Desktop MouseWheel Switching\fR: Das Mausrad wechselt die Arbeitsflaeche wenn sich die Maus ueber dem leeren Desktop oder der Toolbar befindet\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBFluechtige (Dialoge) Fenster dekorieren / Decorate Transient Windows\fR: Wenn diese Option aktiviert wird haben auch fluechtige Fenster, wie etwa Speicher\-Dialoge oder aehniches, einen Rahmen und grips in den Ecken\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBKlick holt in den Vordergrund / Click Raises\fR: Wenn diese Option aktiviert ist holt ein Klick auf einen beliebigen Fensterteil das Fenster in den Vordergrund\. Ansonsten muss auf den Fenstertitel geklickt werden\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBTransparenz / Transparency\fR: setzt Transparenzwerte fuer Fenster (fokussiert/unfokussiert) und das Menue
.RE
.SS "Fenstermenue"
Das Fenstermenue wird bei einem Rechtsklick auf den Fenstertitel oder den Eintrag in der Toolbar angezeigt\. Es enthaelt folgende Eintraege: (uebersetzt / Original)
.sp
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBSenden an / Send To\&...\fR: Platziert das Fenster auf einer anderen Arbeitsflaeche\. Wenn diese mit einem Mittelklick ausgewaehlt wird wechselt fluxbox sofort zu dieser Arbeitsflaeche\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBAufrollen / Shade\fR: Rollt das Fenster auf/ab (nur der Fenstertitel wird angezeigt)\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBMinimieren / Iconify\fR: Minimiert das Fenster\. Es ist dann ueber das Arbeitsflaechenmenue oder die Toolbar anwaehlbar\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBMaximieren / Maximize\fR: Maximiert ein Fenster\. Je nach Maustaste wird das Fenster anders maximiert:
.sp
.RS 4
.nf
Taste 1  Normales Maximieren
Taste 2  Vertikales Maximieren
Taste 3  Horizontales Maximieren
.fi
.RE
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBNach vorne / Raise\fR: Bringt das Fenster ganz nach vorne\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBNach hinten / Lower\fR: Setzt das Fenster ganz nach hinten\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBAuf allen Desktops sichtbar / Stick\fR: Schaltet den Klebezustand des Fenster um\. Wenn das Fenster auf klebrig (sticky) geschaltet ist wird es auf allen Arbeitsflaechen angezeigt\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBEbene / Layer\fR: Setzt das Fenster auf die angegebene Ebene\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBTransparenz / Alpha\fR: Setzt den Transparenzwert des Fensters
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBEinstellungen merken / Remember\&...\fR: Legt fest welche Fenstereigenschaften dauerhaft in der apps Datei gespeichert werden sollen\. Mehr dazu unter ANWENDUNGEN\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBClose\fR: Schliesst die Anwendung\.
.RE
.SS "Arbeitsflaechenmenue"
Das Arbeitsflaechenmenue erscheint bei einem Klick mit der mittleren Maustaste auf den leeren Desktop\. Es ermoeglicht das Hinzufuegen oder Entfernen einer Arbeitslaeche\. Zudem sind alle Arbeitsflaechen mit den sich darauf befindenden Fenstern aufgelistet\. Ein Mittelklick auf den Namen einer Arbeitsflaeche schaltet auf diese um, ein Linksklick auf einen Fensternamen schaltet auf die entsprechende Arbeitsflaeche und fokussiert das gewaehlte Fenster\. Im Icons Untermenue sind zudem alle minimierten Fenster gelistet\.
.sp
.SS "Menueverhalten"
Das Verhalten des Menues kann in der Initdatei festgelegt werden\. Die Optionen sind folgende: (standardmaessig ist fuer beide 0 gesetzt):
.sp
.sp
.RS 4
.nf
session\.screen0\.menuDelay: <msec>
session\.screen0\.menuDelayClose: <msec>
.fi
.RE
.SS "Menu Syntax"
Eine Zeile in der Menue Datei besteht aus 4 Teilen:
.sp
.sp
.RS 4
.nf
[tag] (Bezeichnung) {Befehl|Dateiname} <icon>
.fi
.RE
Die Bezeichnung ist dabei jeweils der Text, der im Menue erscheint\.
.sp
Tags sind:
.PP
[begin] (Titel)
.RS 4
Dieser tag muss unbedingt gesetzt werden, er kennzeichnet den Anfang der Menuedatei\. Der Titel des Menues kann man selber setzen\.
.RE
.PP
[end]
.RS 4
Kennzeichnet den Schluss eines Menues oder Untermenues\. Mindestens ein end tag muss vorhanden sein, zusaetzlich muss jedes Untermenue mit einem end tag geschlossen weden\.
.RE
.PP
[exec] (Bezeichnung) {Befehl}
.RS 4
Fuegt einen Programm\- oder Skriptaufruf in das Menue ein\. Dies ist der haeufigste Eintrag\.
.RE
.PP
[exit] (Bezeichnung)
.RS 4
Beendet fluxbox\.
.RE
.PP
[include] (Datei oder Verzeichnis)
.RS 4
Parst die angegebene Datei Der Dateiname kann eine volle Pfadangabe zu einer Datei oder nur eine Pfadangabe sein\. Wenn keine Datei sondern ein Verzeichnis angegeben wird werden saemtliche Dateien darin verarbeitet\.
.RE
.PP
[nop] (Bezeichnung)
.RS 4
Fuegt einen Dummy ein der keine Funktion hat\. Kann verwendet werden um das Menue in Bloecken zu gruppieren\. Wenn keine Bezeichnung angegeben wird setzt fluxbox einfach eine Leerzeile im Menue\.
.RE
.PP
[separator]
.RS 4
Fuegt eine Trennlinie in das Menue ein\.
.RE
.PP
[style] (Bezeichnung) {Dateiname}
.RS 4
Fuegt ein Farbschema als Menueeintrag hinzu
.RE
.PP
[stylesdir] (Bezeichnung) {Verzeichnis}
.RS 4
Erstellt ein Untermenue mit dem Namen des angegebenen Bezeichners und listet in diesem alle enhaltenen Dateien, die im angegebenen Verzeichnis gefunden werden, als Farbschemata auf\.
.RE
.PP
[stylesmenu] (Verzeichnis)
.RS 4
Liest alle Dateien in dem Verzeichnis und listet sie als Farbschemata auf, die ausgewaehlt werden koennen\.
.RE
.PP
[submenu] (Bezeichnung) {menuetitel}
.RS 4
Erstellt ein neues Untermenue\. Die Angabe eines Menuetitels ist hierbei nicht zwingend\. Verschachtelung ist moeglich, die Untermenues sind in der Tiefe nicht beschraenkt\.
.RE
.PP
[reconfig] (Bezeichnung)
.RS 4
Erstellt einen Menueeintrag, der die Konfigurationsdateien und das Farbschema neu einliest\. Sehr praktisch wenn man ein Farbschema editiert und fluxbox nicht immer neu starten will\.
.RE
.PP
[restart] (Bezeichnung) {Befehl}
.RS 4
Erstellt einen Menuepunkt der fluxbox neu startet oder, wenn ein Befehl angegeben, ist fluxbox beendet und den Befehl ausfuehrt\. (Zum Beispiel um zu einem anderen Fenstermanager zu wechseln)
.RE
.PP
[config] (Bezeichnung)
.RS 4
Fuegt das fluxbox Konfigurationsuntermenue hinzu
.RE
.PP
[wallpapermenu] (Verzeichnis) {Befehl}
.RS 4
Listet alle (Bild)Dateien in dem angegebenen Verzeichnis als Menueintraege auf\. Der Befehl wird benutzt um das Bild als Hintergrund zu setzen\. Wenn kein Befehl angegeben wird nutzt fluxbox fbsetbg(1)
.RE
.PP
[wallpapers] (label)
.RS 4
Synonym für wallpapermenu\.
.RE
.PP
[workspaces] (Bezeichnung)
.RS 4
Fuegt das Arbeitsflaechenmenue zum Menue hinzu, praktisch fuer Leute die das Arbeitsflaechenmenue nicht so aufrufen koennen\. (Zweitastenmaus ohne Emulation des dritten Knopfes)
.RE
Alle Zeilen die mit # oder ! beginnen werden von fluxbox als Kommentar gesehen und ignoriert\. Sonderzeichen koennen mit \e escaped werden\.
.sp
Ein Menue koennte zum Beispiel so aussehen:
.sp
.sp
.RS 4
.nf
# fluxbox menu file
[begin] (fluxbox)
    [exec] (rxvt) {rxvt \-ls} </usr/X11R6/share/icons/terminal\.xpm>
    [exec] (netscape) {netscape \-install}
    [exec] (The GIMP) {gimp}
    [exec] (XV) {xv}
    [exec] (Vim) {rxvt \-geometry 132x60 \-name VIM \-e screen vim}
    [exec] (Mutt) {rxvt \-name mutt \-e mutt}
    [submenu] (mozilla)
        [exec] (browser) {mozilla \-browser}
        [exec] (news) {mozilla \-news}
        [exec] (mail) {mozilla \-mail}
        [exec] (edit) {mozilla \-edit}
        [exec] (compose) {mozilla \-compose}
    [end]
    [submenu] (Window Manager)
        [exec] (Edit Menus) {nedit ~/\.fluxbox/menu}
        [submenu] (Style) {Which Style?}
            [stylesdir] (~/\.fluxbox/styles)
            [stylesmenu] (fluxbox Styles) {@pkgdatadir@/styles}
        [end]
        [config] (Config Options)
        [reconfig] (Reconfigure)
        [restart] (Restart)
    [end]
    [exit] (Log Out)
[end]
.fi
.RE
.SH "TOOLBAR"
Die Toolbar ist ein Platzhalter fuer diverse Werkzeuge, wie zum Beispiel eine Uhr, die Anzeige der aktuellen Arbeitsflaeche, ein Systemabschnitt oder die Iconbar, welche von fluxbox verwaltete Fenster anzeigt\. Ihr aussehen kann in dem Farbschema konfiguriert werden\.
.sp
Die einzelnen Werkzeuge koennen in der init Datei ein/ausgeschaltet werden\. Zudem kann so ihre Platzierung festgelegt werden\. Zustaendig dafuer ist die Zeile
.sp
.sp
.RS 4
.nf
session\.screen0\.Toolbar\.tools
.fi
.RE
Die Anzahl und Reihenfolge der Werkzeuge ist frei waehlbar, einzelne muessen mit einem Komma (,) getrennt werden\. Beispiel:
.sp
.sp
.RS 4
.nf
session\.screen0\.Toolbar\.tools: workspacename, systemtray, iconbar, clock
.fi
.RE
Als Werkzeuge stehen zur Auswahl:
.sp
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBclock\fR: Zeigt die Uhrzeit und je nach Konfiguration das Datum an, das Format wird in der init Datei festgelegt und entspricht dem von "man strtftime"
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBiconbar\fR: Zeigt die von fluxbox verwalteten Fenster an\. Je nach Einstellung alle Fenster, nur minimierte Fenster oder nur die Fenster der aktuellen Arbeitsflaeche\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBsystemtray\fR: Der Systemabschnitt, einige Applikationen koennen sich in die Systemtray minimieren\. Bekannt dafuer sind InstantMessenger wie Gaim/Kopete, Audioplayer wie amaroK oder zum Beispiel Lautstaerkeregler\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBworkspacename\fR: Zeigt den Namen der aktuellen Arbeitsflaeche an
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBprevworkspace\fR: Zeigt einen Knopf mit einem Pfeil an\. Bei Klick wird auf die vorige Arbeitsflaeche umgeschaltet\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBnextworkspace\fR: Zeigt einen Knopf mit einem Pfeil an\. Bei Klick wird auf die naechste Arbeitsflaeche umgeschaltet\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBprevwindow\fR: Zeigt einen Knopf mit einem Pfeil an\. Bei Klick wird das letzte sichtbare Fenster fokussiert\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBnextwindow\fR: Zeigt einen Knopf mit einem Pfeil an\. Bei Klick wird das naechste sichtbare Fenster fokussiert\.
.RE
Alle anderen Dinge koennen auf zwei Arten konfiguriert werden: mit einem Texteditor kann die init Datei manuell bearbeitet werden\. Komfortabler ist das Toolbarmenue, welches mit einem Rechtsklick auf die Toolbar aufgerufen werden kann\.
.sp
.SS "Konfiguration ueber das Toolbarmenue"
Alle aenderungen werden von fluxbox sofort uebernommen, bis auf die Transparenzeinstellungen welche einen Neustart von fluxbox erfordern: (Die Eintraege stehen jeweils uebersetzt und als englisches Original, zudem ist die passende Zeile in der init Datei angegeben)
.sp
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBSichtbar / Visible\fR: Macht die Toolbar sichtbar/unsichtbar\.
.sp
.RS 4
.nf
session\.screen0\.Toolbar\.visible: <boolean>
.fi
.RE
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBAutomatisch Ausblenden / Auto hide\fR: Die Toolbar wird nach der angegebenen Verzoegerung ausgeblendet wenn der Mauszeiger nicht mehr auf ihr ruht\. Ein Bewegen des Mauszeigers auf dem Rand der Toolbar blendet sie wieder ein\.
.sp
.RS 4
.nf
session\.screen0\.Toolbar\.autoHide: <boolean>
session\.autoRaiseDelay: <int>
.fi
.RE
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBToolbar Laenge / Toolbar width percentage\fR: Gibt die Breite der Toolbar im Verhaeltnis zum Bildschirm an\. Ein Linksklick verkleinert den Wert, ein Rechtsklick erhoeht ihn\. Alternativ kann das Mausrad benutzt werden\.
.sp
.RS 4
.nf
session\.screen0\.Toolbar\.widthPercent: <int>
.fi
.RE
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBvon maximierten Fenstern verdecken / Maximize Over\fR: Ermoeglicht das vollstaendige ueberdecken der Toolbar durch ein maximiertes Fenster\. Vollstaendiges Maximieren im Konfigurationsmenue ueberschreibt diese Option\.
.sp
.RS 4
.nf
session\.screen0\.Toolbar\.maxOver: <boolean>
session\.screen0\.fullMaximization: <boolean>
.fi
.RE
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBEbene / Layer\fR: Die Toolbar wird auf die angegebene Ebene gesetzt\. Somit kann sie auf Wunsch alle Fenster ueberdecken\.
.sp
.RS 4
.nf
session\.screen0\.Toolbar\.layer: <layer>
.fi
.RE
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBPlatzierung / Placement\fR: Platziert die Toolbar an einem Bildschirmrand, entweder zentriert oder an einer Ecke ausgerichtet\.
.sp
.RS 4
.nf
session\.screen0\.Toolbar\.placement: <direction>
.fi
.RE
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBTransparenz / Alpha\fR: Definiert wie durchsichtig die Toolbar sein soll\. Bei einem Wert von 0 ist sie unsichtbar, bei einem Wert von 255 gar nicht transparent\. Text ist niemals transparent\.
.sp
.RS 4
.nf
session\.screen0\.Toolbar\.alpha: <int>
.fi
.RE
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBSymbolleistenmodus / Iconbar Mode\fR:
.sp
.RS 4
.nf
Gibt an welche Fenster in der Symbolleiste angezeigt werden:
.fi
.RE
.sp
.RS 4
.nf
Keine / None:
    Zeigt gar keine
Symbole / Icons:
    Zeigt die minimierten Fenster aller Arbeitsflaechen
Keine Symbole / NoIcons:
    Zeigt die nicht minimierten Fenster aller Arbeitsflaechen
Arbeitsflaeche: Symbole / WorkspaceIcons:
    Zeigt alle minimierten Fenster der aktuellen Arbeitsflaeche
Arbeitsflaeche: Keine Symbole / WorkspaceNoIcons:
    Zeigt alle nicht minimierten Fenster der aktuellen Arbeitsflaeche
    (iconified)
Arbeitsflaeche / Workspace:
    Zeigt alle Fenster der aktuellen Arbeitsflaeche
Alle Fenster / All Windows:
    Zeigt alle Fenster aller Arbeitsflaechen
.fi
.RE
.sp
.RS 4
.nf
session\.screen0\.iconbar\.mode: <mode>
.fi
.RE
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBAusrichtung\fR:
.sp
.RS 4
.nf
Links / Left:
    Alle Fenstereintraege werden linksbuendig angezeigt
Relativ / Relative:
    Die Fenstereintraege werden so breit gezeigt, dass die Iconbar voll ist
Rechts / Right:
    Alle Fenstereintraege werden rechtsbuendig angezeigt
.fi
.RE
.sp
.RS 4
.nf
session\.screen0\.iconbar\.alignment: <alignment>
session\.screen0\.iconbar\.iconWidth: <int>
.fi
.RE
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBProgramm\-Icons anzeigen / Show Pictures\fR: Wenn diese Einstellung aktiv ist werden die Icons (in diesem Fall Bilder) neben dem Programmnamen angezeigt\.
.sp
.RS 4
.nf
session\.screen0\.iconbar\.usePixmap: <boolean>
.fi
.RE
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBZeitformat / Clock\fR: Ermoeglicht eine Umstellung vom 12 zum 24 Stunden Format
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBUhrformat bearbeiten / Edit Clock Format\fR: Ein kleines Fenster zum Bearbeiten des Uhrformates wird angezeigt\. Die Formatierung ist wie in man strftime beschrieben\.
.sp
.RS 4
.nf
session\.screen0\.strftimeFormat: <format>
.fi
.RE
.RE
.SH "RESSOURCEN"
Ueblicherweise wird die ~/\.fluxbox/init Datei von fluxbox erstellt und verwaltet\. Fast alle Einstellungen koennen ueber das Konfigurationsmenue vorgenommen werden\. Wenn die Datei von Hand editiert wird muss fluxbox neu gestartet werden damit aenderungen uebernommen werden\.
.sp
Wenn fluxbox auf mehreren Bildschirmen laeuft muss screen0 je nach dem angepasst werden\. Einstellungen koennen fuer jeden Bildschirm einzeln vorgenommen werden\.
.sp
Folgende Optionen koennen in der Init Datei angepasst werden:
.sp
.sp
.RS 4
.nf
Transparenz (alpha)

session\.screen0\.menu\.alpha: <integer>
session\.screen0\.slit\.alpha: <integer>
session\.screen0\.Toolbar\.alpha: <integer>
session\.screen0\.window\.focus\.alpha: <integer>
session\.screen0\.window\.unfocus\.alpha: <integer>
    Mit diesen Zeilen kann die Transparenz der einzelnen
    fluxboxkomponenten angepasst werden\. Der Wert ist dabei
    eine Ganzzahl zwischen 0 und 255, wobei 0 vollstaendig
    transparent und 255 deaktivierte Transparenz bedeutet\.
    Standardwert: 255

Automatisches Ausblenden (autohide)

session\.screen0\.slit\.autoHide: <boolean>
session\.screen0\.Toolbar\.autoHide: <boolean>
    Mit diesen Einstellungen kann man bewirken, dass
    Toolbar oder slit bei Nichtgebrauch automatisch ausgeblendet werden\.
    Der Wert ist dabei true (aktiviert) oder false (staendig sichtbar)
    Standardwert: false

Mausrad (wheeling)

session\.screen0\.desktopwheeling: <boolean>
    Sind diese Einstellungen aktiviert (true) kann mit dem
    Mausrad zwischen den Arbeitsflaechen umgeschaltet werden
    wenn sich die Maus ueber einem freien Desktopbereich befindet\.
    Standardwert: true

Ebenen (layer)

session\.screen0\.slit\.layer: <layer>
session\.screen0\.Toolbar\.layer: <layer>
    Ebene auf der sich Slit und Toolbar befinden
    Standardwert: Desktop

onTop Einstellungen

session\.screen0\.slit\.onTop: <boolean>
session\.screen0\.Toolbar\.onTop: <boolean>
     Werden diese Einstellungen aktiviert befinden sich
     Toolbar/Slit immer oberhalb aller anderer Fenster
     Standardwert: False

Standort (placement)

session\.screen0\.slit\.placement: <placement>
session\.screen0\.Toolbar\.placement: <placement>
    Standort von Toolbar und Slit\. Moegliche Optionen sind:
    \-   BottomCenter    Unten zentriert
    \-   BottomLeft      Unten links
    \-   BottomRight     Unten rechts
    \-   LeftCenter      Links zentriert
    \-   RightCenter     Rechts zentriert
    \-   TopCenter       Oben zentriert
    \-   TopLeft         Oben links
    \-   TopRight        Oben rechts

maxOver

session\.screen0\.slit\.maxOver: <boolean>
session\.screen0\.Toolbar\.maxOver: <boolean>
    Sind diese Einstellungen aktiviert ueberdecken
    maximierte Fenster die Toolbar/den Slit\.
    Standardwert: false

Toolbar

session\.screen0\.Toolbar\.height: <integer>
    Hier kann die Hoehe der Toolbar eingestellt werden\.
    Wird sie auf 0 gesetzt bestimmt der verwendete
    Stil wie hoch sie ist
    Standardwert: 0

session\.screen0\.Toolbar\.visible: <boolean>
    Wird diese Option deaktiviert (false) ist die
    Toolbar komplett ausgeblendet
    Standardwert: true

session\.screen0\.Toolbar\.widthPercent: <integer>
    Die Breite der Toolbar, angegeben in Prozent der Bildschirmbreite
    Standardwert: 100

session\.screen0\.Toolbar\.tools: <tools>
    Definiert welche Werkzeuge die Toolbar zur Verfuegung stellen soll\.
    Mehr dazu steht im Abschnitt Toolbar in der manpage\.
    Moegliche Auswahl:
    \-   clock   (Uhr)
    \-   iconbar  (Fensterleiste)
    \-   nextwindow  (Naechstes Fenster)
    \-   prevwindow  (Vorheriges Fenster)
    \-   nextworkspace  (Naechste Arbeitsflaeche)
    \-   prevworkspace (Vorherige Arbeitsflaeche)
    \-   systemtray  (Systemabschnitt)
    \-   workspacename  (Name der Arbeitsflaeche)

session\.screen0\.slit\.onhead: <integer>
session\.screen0\.Toolbar\.onhead: <integer>
    Bestimmt bei Systemen mit mehreren Monitoren auf welchem
    sich die Toolbar/der Slit befinden
    Standardwert: 0

session\.screen0\.slit\.direction: <alignment>
    Ausrichtung des Slits, Horizontal oder Vertikal

Iconbar

session\.screen0\.iconbar\.mode: <mode>
    Welche Fenster sollen in der Fensterleiste angezeigt werden?
    \-   All Windows  (alle)
    \-   Icons  (minimierte)
    \-   None  (keine)
    \-   Workspace  (alle der aktuellen Arbeitsflaeche)
    \-   WorkspaceIcons  (alle minimierten der aktuellen Arbeitsflaeche)

session\.screen0\.iconbar\.usePixmap: <boolean>
    Sollen Icons in der Fensterleiste angezeigt werden?
    Ja (true) oder nein (false)
    Standardwert: true

session\.screen0\.iconbar\.iconTextPadding: <integer>
session\.screen0\.iconbar\.deiconifyMode: Current
session\.screen0\.iconbar\.wheelMode: Screen
session\.screen0\.iconbar\.alignment: <position>
    Anordnung der Eintraege in der Fensterleiste
    Zur Auswahl stehen:
    \-   Left: Feste Breite, linksbuendig
    \-   Relative: flexible Breite
    \-   Right: Feste Breite, rechtsbuendig
    Standardwert: Relative

Reiter (tabs)

session\.screen0\.tab\.alignment: Left
    Anordnung der Reiter (tabs)

session\.screen0\.tab\.height: 16
    Hoehe der Reiter (tabs)

session\.screen0\.tab\.placement: <position>
        Platzierung der Reiter (tabs)
        moeglich ist:
        \-       TopLeft
        \-       LeftTop
        \-       LeftBottom
        \-       BottomLeft
        \-       TopRight
        \-       RightTop
        \-       RightBottom
        \-       BottomRight

session\.screen0\.tab\.rotatevertical: True
session\.screen0\.tab\.width: 64
    Breite der Reiter (tabs)

Magneteffekt

session\.screen0\.edgeSnapThreshold: <integer>
    Magneteffekt, damit Fenster sich an anderen oder an
    den Seitenraendern festkleben\. Die Zahl gibt den Abstand
    an ab dem dieser Effekt aktiviert wird
    Standardwert: 0

Diverses

session\.screen0\.followModel: Ignore
session\.screen0\.rowPlacementDirection: LeftToRight
session\.screen0\.colPlacementDirection: TopToBottom
    Konfiguriert das Vehalten der Fensterplatzierung

session\.screen0\.resizeMode: Bottom
    Konfiguriert die Art der Fenstervergroesserung

session\.screen0\.focusModel: ClickToFocus
    Setzt das Fokusmodell

session\.screen0\.autoRaise: <boolean>
session\.screen0\.clickRaises: <boolean>
    Konfiguriert das Verhalten beim Anheben von Fenstern

session\.screen0\.workspacewarping: <boolean>
    Ist diese Option aktiviert koennen Fenster auf eine
    andere Arbeitsflaeche gezogen werden\.
    Standardwert: true

session\.screen0\.showwindowposition: <boolean>
    Ist diese Option aktiviert wird beim Verschieben/Vergroessern
    eines Fensters die momentane Position/Groesse in Form
    von  x/y eingeblendet
    Standardwert: true

session\.screen0\.decorateTransient: <boolean>
session\.screen0\.workspaceNames: workspace1, workspaceN
    Standardwert: one, two, three, four

session\.screen0\.strftimeFormat: <date>
    Format der Uhr in der Toolbar\. Naeheres dazu in der manpage von strftime(3)
    Standardwert: %I:%M %p

session\.screen0\.windowPlacement: <Strategie>
    Diese Option gibt an wie fluxbox neue Fenster automatisch platzieren soll
    RowSmartPlacement reiht die Fenster ueberlappend auf,
    ColSmartPlacement reiht sie ohne Ueberlappung nebeneinander,
    CascadePlacement setzt es unter den Fenstertitel des letzten Fensters,
    UnderMousePlacement setzt sie unter die aktuelle Mausposition
    Standardwert: RowSmartPlacement

session\.screen0\.rowPlacementDirection: LeftToRight|RightToLeft
session\.screen0\.colPlacementDirection: TopToBottom|BottomToTop
    Setzt die Richtung in der fluxbox neue Fenster bei
    RowSmartPlacement respektive ColSmartPlacement setzen soll\.

session\.screen0\.workspaces: <integer>
    Anzahl Arbeitsflaechen
    Standardwert: 4

session\.appsFile: <Pfad>
session\.groupFile: <Pfad>
session\.keyFile: <Pfad>
session\.menuFile: <Pfad>
session\.slitlistFile: <Pfad>
session\.styleFile: <Pfad>
    Standort der Konfigurationsdateien\. Normalerweise werden
    die Dateien im ~/\.fluxbox Verzeichnis abgelegt/verwendet

session\.doubleClickInterval: <integer>
    Abstand (in Millisekunden) zwischen zwei Mausklicks damit
    diese noch als Doppelklick gewertet werden
    Standardwert: 250

session\.forcePseudoTransparency: <boolean>
    Erzwingt Pseudotransparenz ueber echte Transparenz

session\.opaqueMove: <boolean>
    Anzeigen des Inhalts beim Verschieben eines Fensters\.
    Sollte auf langsamen Systemen deaktiviert (false) werden
    Standardwert: true

session\.tabs: <boolean>
session\.tabsAttachArea: Window
    Aktiviert/Deaktiviert Tabs und setzt sie
    innerhalb oder ausserhalb des Fensters

session\.titlebar\.left: Stick
session\.titlebar\.right: Minimize Maximize Close
    Welche Knoepfe sollen im Fenstertitel angezeigt werden,
    in welcher Reihenfolge und auf welcher Seite\.
    Auswahl:
    Stick (Klebezustand)
    Menu (Fenstermenue)
    Shade (Auf/Abrollen)
    Minimize (Minimieren)
    Maximize (Maximieren)
    Close (Schliessen)
.fi
.RE
.SH "TASTEN"
Tastenkombinationen koennen in der Datei ~/\.fluxbox/keys festgelegt werden\. Das Format der Eintraege ist wie folgt:
.sp
KeyMode <Modtaste> <Taste> :<Befehl>
.sp
Dabei ist Mod1 die ALT Taste, Control ist Ctrl/Strg, Shift ist die Shifttaste und Mod4 die Windowstaste\. None als Modtaste bewirkt, dass der Befehl bei direktem Druck auf <Taste> ausgefuehrt wird\.
.sp
Eine Liste der moeglichen Modtasten liefert \fIxmodmap \-pm\fR\. Diese Zeigt auch welche Taste mit welchem Modifikator belegt ist\.
.sp
Neu koennen auch Maustasten (Mouse1, Mouse2 etc\.) belegt werden\.
.sp
Eine keys Datei koennte so aussehen:
.sp
.sp
.RS 4
.nf
# fluxbox keys file\.
OnDesktop Mouse1 :hideMenus
OnDesktop Mouse2 :workspaceMenu
OnDesktop Mouse3 :rootMenu
OnDesktop Mouse4 :nextWorkspace
OnDesktop Mouse5 :prevWorkspace
OnToolbar Mouse4 :nextWorkspace
OnToolbar Mouse5 :prevWorkspace

Mod1 Tab :NextWindow
Mod1 Shift Tab :PrevWindow
Mod1 F1 :Workspace 1
Mod1 F2 :Workspace 2
Mod1 F3 :Workspace 3
Mod1 F4 :Workspace 4
Mod1 F5 :Workspace 5
Mod1 F6 :Workspace 6
Mod1 F7 :Workspace 7
Mod1 F8 :Workspace 8
Mod1 F9 :Workspace 9
Mod4 b :PrevWorkspace
Mod4 c :Minimize
Mod4 r :ExecCommand rxvt
Mod4 v :NextWorkspace
Mod4 x :Close
Mod4 m :RootMenu
Control n Mod1 n :NextTab
.fi
.RE
Die letzte Zeile zeigt, dass auch Tastensketten wie zum Beispiel von Emacs bekannt verwendet werden koennen
.sp
Wichtig zu wissen: Befehle sind case\-insensitive Die Arbeitsflaechen beginnen bei "1" Fuer diverse Befehle gibt es Synonyme\. Der Abstand zwischen der letzten Taste und dem ":" ist zwingend\.
.sp
.SS "Window\-Manager\-Befehle"
.sp
.RS 4
\h'-04'\(bu\h'+03'Restart <argument> #Startet fluxbox neu
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Quit #Beendet fluxbox
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Exit #Beendet fluxbox
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Reconfigure #Liest die Konfiguration neu ein
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Reload Style #Laedt den verwendeten Stil neu
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'SetStyle <argument> #Schaltet zu dem gewaehlten Stil
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'ExecCommand <argument> #Fuehrt einen Befehl aus
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Exec <argument> #Fuehrt einen Befehl aus
.RE
.SS "Befehle fuer das fokussierte Fenster"
.sp
.RS 4
\h'-04'\(bu\h'+03'Fullscreen #Schaltet das Fenster auf Vollbild
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Minimize #Minimiert das Fenster
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'MinimizeWindow #Minimiert das Fenster
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Iconify #Minimiert das Fenster
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Maximize #Maximiert das Fenster
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'MaximizeWindow #Maximiert das Fenster
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'MaximizeHorizontal #Maximiert das Fenster horizontal
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'MaximizeVertical #Maximiert das Fenster vertikal
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'ResizeTo <breite> <hoehe> #aendert die Fenstergroesse
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Resize <delta\-breite> <delta\-hoehe> #Siehe weiter unten
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'ResizeHorizontal <delta\-breite> #Siehe weiter unten
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'ResizeVertical <delta\-hoehe> #Siehe weiter unten
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'MoveTo <x> <y> <Ecke> #Siehe weiter unten
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Move <delta\-x> <delta\-y> #Siehe weiter unten
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'MoveRight <delta\-x> #Siehe weiter unten
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'MoveLeft <delta\-x> #Siehe weiter unten
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'MoveUp <delta\-y> #Siehe weiter unten
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'MoveDown <delta\-y> #Siehe weiter unten
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Raise #Bringt das Fenster in den Vordergrund
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'RaiseLayer #Bringt das Fenster eine Ebene nach vorne
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Lower #Bringt das Fenster in den Hintergrund
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'LowerLayer #Bringt das Fenster eine Ebene nach hinten
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Close #Schliesst das Fenster
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Shade #Schliesst das Fenster
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'ShadeWindow #Rollt das Fenster auf/ab
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Stick #Schaltet den Klebezustand um
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'StickWindow #Schaltet den Klebezustand um
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'ToggleDecor #Deaktiviert den Fensterrahmen
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'SendToWorkspace <Arbeitsflaeche> #Verschiebt das Fenster auf Arbeitsflaeche
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'SendToNextWorkspace <nummer> #Verschiebt das Fenster auf Flaeche + Nummer
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'SendToPrevWorkspace <number> #Verschiebt das Fenster auf Flaeche \- Nummer
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'TakeToWorkspace <num> #Zeigt die neue Arbeitsfläche gleich an
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'KillWindow #Forciert das Schliessen des Fensters (kill)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'NextTab #Schaltet zum naechsten Reiter um
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'PrevTab #Schaltet zum vorherigen Reiter um
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'MoveTabLeft #Verschiebt das Fenster nach links
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'MoveTabRight #Verschiebt das Fenster nach rechts
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'DetachClient #Loest das Fenster von einer Gruppe
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'SetHead <int> #Verschiebt das Fenster auf Bildschirm <int>
.RE
.SS "Befehle fuer die Arbeitsflaeche"
.sp
.RS 4
\h'-04'\(bu\h'+03'NextWorkspace #Schaltet zur naechsten Arbeitsflaeche
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'PrevWorkspace #Schaltet zur vorherigen Arbeitsflaeche
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'RightWorkspace <anzahl> #Schaltet um "anzahl" nach rechts
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'LeftWorkspace <anzahl> #Schaltet um "anzahl" nach links
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Workspace <n> #Schaltet zur Arbeitsflaeche n
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'NextWindow <bitmask> #siehe weiter unten
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'PrevWindow <bitmask> #siehe weiter unten
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'ArrangeWindows #Ordnet die Fenster nebeneinander an
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'ShowDesktop #Minimiert alle Fenster der Arbeitsflaeche
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'RootMenu #Zeigt das fluxboxmenu an
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'WorkspaceMenu #Zeigt das Arbeitsflaechenmenu an
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'WindowMenu #Zeigt das Fenstermenue an
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'SetWorkspaceName <name> #Bennennt die aktuelle Arbeitslaeche um
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'ShowDesktop #Minimiert alle Fenster
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Deiconify all|allworkspace|last|lastworkspace current|origin|originquiet
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'FocusUp #Fokussiert das noerdlich liegende Fenster
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'FocusDown #Fokussiert das suedlich liegende Fenster
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'FocusLeft #Fokussiert das westlich liegende Fenster
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'FocusRight #Fokussiert das oestlich liegende Fenster
.RE
.SS "Spezielle Befehle"
.sp
.RS 4
\h'-04'\(bu\h'+03'MacroCmd #Befehlsreihen, MacroCmd {command1} {command2}\&...
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'ReloadStyle #Der Stil wird neu geladen
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'SetResourceValue <resourcename> <resource> wert
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'BindKey <key><value>: <action> #Weist eine Taste einem Befehl zu
.RE
.SS "Diverses"
.sp
.RS 4
\h'-04'\(bu\h'+03'Exec: fluxbox nutzt /bin/sh um Befehle auszuefuehren\. Will heissen, dass man Umgebungsvariablen nutzen kann\. :Exec $XTERM Sartet zum Beispiel das der Variable $XTERM zugewiesene Terminal\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'TakeToWorkspace: Sendet das Fenster an eine bestimmte Arbeitsflaeche und schaltet anschliessend auch zu dieser um\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'TakeToNextWorkspace <offset>: Sendet das Fenster an die aktuelle Arbeitsflaeche + Offset und schaltet zu ebendieser um\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'PrevWindow/NextWindow braucht eine Zahl als Parameter: 0 oder nichts = aktuelles / Standardverhalten 1 = Nur ein Tab pro Gruppe 2 = Keine klebenden Fenster 4 = Keine aufgerollten Fenster 8 = Lineares Umschalten zwischen allen Fenstern 16 = Keine minimierten Fenster
.sp
.RS 4
.nf
Diese Optionen koennen miteinander kombiniert werden,
dazu muss man nur die entsprechenden Zahlen addieren
und das Ergebnis als Parameter nehmen\.
.fi
.RE
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'KeyMode ermoeglicht es verschiedene Gruppen von Tastenzuweisungen zu haben, die nicht alle gleichzeitig aktiv sind\. Zum Beispiel kann man per
\fIKeyMode Xnest\fR
zum XNest Modus wechseln, bei dem alle Tastenzuweisungen, die nicht mit Xnest: beginnen, deaktiviert sind\. <return key sequence> schaltet auf den Standardmodus\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Der Delta\-Wert entspricht der Differenz zischen dem aktuellen und dem gewuenschten Wert\. Nehmen wir an ein Fenster ist 100 Pixel breit
.RE
.sp
.RS 4
.nf
Mod1 r :ResizeHorizontal 10
.fi
.RE
wuerde das Fenster auf 110 Pixel vergroessern,
.sp
.sp
.RS 4
.nf
Mod1 R :ResizeHorizontal \-10
.fi
.RE
verkleinert es um 10, also auf 90 Pixel\.
.sp
.sp
.RS 4
\h'-04'\(bu\h'+03'MacroCmd:
.RE
.sp
.RS 4
.nf
Mod1 r :MacroCmd {Befehl1} {Befehl2}
.fi
.RE
.sp
.RS 4
.nf
Ermoeglicht das serielle ausfuehren mehrerer Befehle\.
.fi
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'ToggleCmd:
.RE
.sp
.RS 4
.nf
Mod1 t :ToggleCmd {command1} {command2}
.fi
.RE
.sp
.RS 4
.nf
Wechselt zwischen den Kommandos bei jedem Tastendruck
.fi
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'SetAlpha [[\-]<int> [[\-]<int>]]: Beinflusst nur das aktuelle Fenster\. Die Parameter sind:
.sp
.RS 4
\h'-04'\(bu\h'+03'keine: Standard wiederherstellen
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Eine Zahl: Setzt den Wert fuer fokussierte und unfokussierte Fenster
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'zwei Zahlen: erste fuer fokussierte, zweite fuer unfokussierte Fenster
.RE
.RE
.SH "EBENEN"
Ebenen beinflussen die Fensterreihenfolge, ergo welche Fenster ueber welchen stehen\. Eine Anwendung auf einer hoeheren Ebene liegt immer ueber einer Anwendung auf einer tieferen Ebene und ueberdeckt diese, selbst wenn die hintere den Fokus hat\.
.sp
Es gibt zwei Moeglichkeiten die Ebene einer Anwendung festzulegen: Entweder ueber das Fenstermenue, welches 6 Ebenen zur Auswahl bietet:
.sp
.sp
.RS 4
\h'-04'\(bu\h'+03'2 \- ueber Dock
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'4 \- Dock
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'6 \- Oben
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'8 \- Normal
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'10 \- Unten
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'12 \- Desktop
.RE
Die andere Moeglichkeit ist die apps Datei, die weiter unten im Abschnitt ANWENDUNGEN beschrieben wird\.
.sp
.SH "FOKUS"
Das Fokusmodell definiert wie ein Fenster den Fokus bekommen kann\. (Will heissen: wie es das aktive Fenster, welches Maus und Tastatureingaben entgegennimmt, wird) Das Fokusmodell kann im Konfigurationsmenue, welches sich im Root Menue befindet, ausgewaehlt werden\.
.sp
Zur Auswahl stehen 4 Optionen, von den oberen beiden und von den unteren beiden sollte jeweils eine gewaehlt werden\.
.sp
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBClick To Focus\fR: Mausklick fokussiert ein Fenster
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBMouse Focus\fR: Ein Fenster wird fokussiert wenn sich die Maus darueber befindet
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBClickTabFocus\fR: Mausklick fokussiert ein Reiter (Tab)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBMouseTabFocus\fR: Der Reiter unter der Maus wird fokussiert
.RE
Die letzte Option automatisches Hervorheben bewirkt, dass ein neu fokussiertes Fenster ueber die anderen Fenster auf der selben Ebene gehoben wird\.
.sp
.SH "REITER OPTIONEN"
In dem Teil des Konfigurationsmenues koennen die Reiter (Tabs) konfiguriert werden\. Er besteht aus 3 Optionen:
.sp
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBPlatzierung / Placement\fR: Gibt an wo sich die externen Reiter am Fenster befinden:
.sp
.RS 4
.nf
Oben Links / Top Left
Oben Rechts / Top Right
Links Oben / Left Top
Rechts Oben / Right Top
Links Unten / Left Bottom
Rechts Unten / Right Bottom
Unten Links / Bottom Left
Unten Rechts / Bottom Right
.fi
.RE
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBTabs in der Titelleiste / Tabs in Titlebar\fR: Diese Option platziert die Tabs im Fenstertitel anstelle von aussen am Fenster\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBvon maximierten Fenstern verdecken / Maximize Over\fR: Wenn diese Option eingeschaltet wird werden externe Tabs beim Maximieren von Fenstern nicht beachtet\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBBreite fuer externe Tabs / External Tab Width\fR: Die Breite der externen Tabs in Pixel
.RE
.SH "FARBSCHEMATA"
Das Aussehen von fluxbox, also die Schriftart, die Fensterdekoration inklusive Fenstertitel, Rahmen, Knoepfe, Menuefarbe, kann bis ins Detail angepasst werden\. Dafuer zustaendig sind Farbschemata, eigentlich ganz normale Textdateien die gewisse Informationen beinhalten\. Naeheres dazu steht in der separaten Anleitung fluxstyle(1)
.sp
.SH "STYLE OVERLAY"
Zusaetzlich zu dem Farbschema gibt es noch das Overlay, welches in der init Datei mit session\.screen0\.styleOverlay (standard: ~/\.fluxbox/overlay ) festgelegt ist\. Darin koennen diverse Konfigurationen des Aussehens von fluxbox so gesetzt werden, dass sie die Einstellungen in dem verwendeten Farbschema ueberschreiben\. Mehr dazu steht auch in fluxstyle(1)\.
.sp
.SH "ANWENDUNGEN"
fluxbox kann diverse Fenstereinstellungen dauerhaft speichern\. Dazu wird die apps Datei benutzt\. Diese kann entweder von Hand angepasst werden oder man fuegt die Eintraege ueber das Fenstermenue der entsprechenden Anwendung hinzu\.
.sp
Das Format fuer Eintraege in der apps Datei sieht wie folgt aus:
.sp
.sp
.RS 4
.nf
[app] (Name der Anwendung)
        [Einstellung1]  /{Wert1/}
        [Einstellung2]  /{Wert2/}
        \.\.\.
[end]
.fi
.RE
Der Name kann dabei ein String oder ein regulaerer Ausdruck (RegExp) sein\. Dabei koennen diverse Dinge als Name verwendet werden, unter anderem der im Fenstertitel erscheinende Name oder auch die "Rolle" des Fensters\. Diese Werte koennen sehr gut mit dem Programm xprop ausgelesen werden\.
.sp
\fBEin paar Beispiele\fR
.sp
.sp
.RS 4
.nf
# Ein Standard XTerm ohne speziell gesetzten Titel:
[app] (xterm)
    \.\.\. Einstellungen \.\.\.
[end]
.fi
.RE
.sp
.RS 4
.nf
# Ein XTerm mit speziell gesetztem Titel: (xterm \-name myshell)
[app] (myshell)
    \.\.\. Einstellungen \.\.\.
[end]
.fi
.RE
.sp
.RS 4
.nf
# Ein beliebiges Firefox Fenster
[app] (class=Firefox\-bin) {1}
    \.\.\. Einstellungen \.\.\.
[end]
.fi
.RE
.sp
.RS 4
.nf
# Die Kontaktliste von GAIM (allerdings nicht das Chatfenster)
[app] (role=buddy_list)
    \.\.\. Einstellungen \.\.\.
[end]
.fi
.RE
.sp
.RS 4
.nf
#Ein RDesktop Fenster zu einem bestimmten Host:
[app] (title=rdesktop \- hostname\.*)
    \.\.\. Einstellungen \.\.\.
[end]
.fi
.RE
\fBEinstellungen\fR
.sp
Folgende Einstellungen koennen pro [app] Eintrag gemacht werden: (Die Bezeichnung ist dabei in eckigen, der wert in geschweiften Klammern zu schreiben)
.sp
.sp
.RS 4
\h'-04'\(bu\h'+03'[Workspace] /{0\-N/} oeffnet die Anwendung auf der angegeben Arbeitsflaeche\. Die Arbeitsflaechen werden von 0 hochgezaehlt\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'[Dimensions] /{Width Height/}: Setzt die Groesse einer Anwendung (Breite Hoehe)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'[Position] (refspot)) /{X Y/}: Position der Anwendung, relativ zu:
.sp
.RS 4
\h'-04'\(bu\h'+03'WINCENTER Fenstermitte
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'CENTER Bildschirmmitte
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'UPPERLEFT Obere linke Ecke
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'UPPERRIGHT Obere rechte Ecke
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'LOWERLEFT Untere linke Ecke
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'LOWERRIGHT Untere rechte Ecke
.sp
.RS 4
.nf
Wird kein Referenzpunkt angegeben geht fluxbox
von der linken oberen Ecke aus\.
.fi
.RE
.RE
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'[Layer] Ebene auf der die Anwendung gestartet wird\. (in Klammern die Originalnamen):
.sp
.RS 4
\h'-04'\(bu\h'+03'2 \- ueber Dock (AboveDock)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'4 \- Dock
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'6 \- Oben (Top)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'8 \- Normal
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'10 \- Unten (Bottom)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'12 \- Desktop
.RE
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'[Shaded] Soll das Fenster aufgerollt gestartet werden
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'[Tab] Ist das Fenster tabbar
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'[IconHidden] Soll das Fenster in der Fensterleiste gezeigt werden
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'[FocusHidden] Soll das Fenster von Prev/NextWindow ausgenommen werden
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'[Hidden] Aktiviert sowohl [IconHidden] als auch [FocusHidden]
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'[Deco] /{NONE|NORMAL|TOOL|TINY|BORDER|TAB/} Definiert aktive Fensterdekos
.sp
.RS 4
\h'-04'\(bu\h'+03'NORMAL \- Standarddekoration
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'NONE \- Ohne Dekoration (Ohne Fenstertitel, ohne Rahmen)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'BORDER \- Nur einen Fensterrahmen aber ohne Titel
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'TINY \- Fenstertitel nur mit Minimieren\-Knopf
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'TOOL \- Nur ein Fenstertitel
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'TAB \- Wie NONE, allerdings werden externe Reiter (tabs) angezeigt
.sp
.RS 4
.nf
Eine Bitmask kann fuer die Einstellung verwendet werden, die bits sind
(von "1" bis 1<<10): Fenstertitel, handle/grips, Rahmen, minimieren,
maximieren, schliessen, Menue aktiviert, Klebezustandsknopf, Aufrollknopf,
Reiter aktiviert, Fokus aktiviert\.
.fi
.RE
.RE
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'[Sticky] Wird das Fenster auf allen Arbeitsflaechen angezeigt
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'[Close] Sollen die Einstellungen beim Schliessen gespeichert werden
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'[Alpha] {int [int]} Setzt die Transparenz fuer das Fenster
.RE
Fenster koennen mit Hilfe der Apps Datei gruppiert werden:
.sp
.sp
.RS 4
.nf
[app] (Eigenschaft=expr) \.\.\. {number}
.fi
.RE
Eigenschaften koennen sein:
.sp
o name \- Fenstername (erstes WM_CLASS Feld) o class \- Fensterklasse (zweites WM_CLASS Feld) o title \- Fenstertitel ( WM_NAME Wert) o role \- Fensterrolle (WM_WINDOW_ROLE Wert)
.sp
Standardmaessig wird als Eigenschaft der Fenstername angenommen\. Diese Informationen kann man mit hilfe von xprop(1) bekommen\.
.sp
Die apps Datei kann auch als Autostart verwendet werden, allerdings ist dies noch nicht direkt ueber das Menue konfigurierbar und die startup Datei sollte ausreichen\.
.sp
Es folgt ein kleines Beispiel einer solchen Datei:
.sp
.sp
.RS 4
.nf
    [startup] {xterm}
    # Betrifft alle Term Fenster, bis zu zwei Instanzen
    [app] (\.*[tT]erm) {2}
    # Betrifft alle Fenster mit *gaim* im Titel
    [app] (title=\.*gaim\.*)
    [app] (kate)
        [Dimensions]  {1022 747}
        [Position]    (WINCENTER) {0 0}
        [Close]       {yes}
    [end]
    [app] (konqueror)
        [Workspace]   {1}
        [Dimensions]  {1006 749}
        [Position]    {16 0}
        [Jump]        {yes}
    [end]
    # Alle Aterms ohne Fensterdekorationen
    [app] (aterm)
        [Deco]        {NONE}
    [end]
    # Eine Gruppe mit GIMP Dock und Toolbox
    # wir auf die vierte Ebene gesetzt
    [group]
      [app] (gimp) (role=gimp\-dock)
      [app] (gimp) (role=gimp\-toolbox)
        [Layer] {4}
    [end]
.fi
.RE
.SH "DER SLIT"
Der Slit ist ein Platz an dem sich diverse Applikationen wie zum Beispiel die BB Tools oder gkrellm andocken koennen\.
.sp
Anwendungen im Slit haben keinen Rahmen, keine Dekoration, sind auf allen Arbeitsflaechen sichtbar und werden nicht wie normale Fenster behandelt\.
.sp
Viele Anwendungen nutzen die \-w Option um in den Slit verschoben zu werden\. Beispiele sind (aus einer xinitrc):
.sp
.sp
.RS 4
.nf
bbmail \-w &
bbpager \-w &
wmdrawer &
exec fluxbox
.fi
.RE
Die Slitfunktionalitaet wird standardmaessig in fluxbox einkompiliert, kann aber entfernt werden\. fluxbox \-i gibt dabei aus ob sie einkompiliert wurde oder nicht\.
.sp
.SH "SLIT MENUE"
Bei einem Rechtsklick auf den Rahmen des Slits oeffnet sich das Slitmenue, welches folgende Konfigurationsmoeglichkeiten bietet:
.sp
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBPlatzierung / Placement\fR: Legt fest wo sich der Slit befindet\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBEbene / Layer\fR: Legt fest auf welcher Ebene sich der Slit befindet\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBAutomatisches Ausblenden / Auto hide\fR: Genau gleich wie das automatische Ausblenden der Toolbar, der Slit wird ausgeblendet wenn sich die Maus eine gewisse Zeit nicht mehr darueber befindet\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBvon maximierten Fenstern verdecken / Maximize over\fR: Wenn diese Option eingeschaltet ist werden maximierte Fenster ueber/unter den Slit gelegt\. Ansonsten wird das Fenster nur bis zum Slit maximiert\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBTransparenz / Alpha\fR: Mit dieser Einstellung kann die Transparenz des Slits (achtung: nur des Slits, nicht der Anwendungen darin) festgelegt werden\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBAusrichtung / Slit direction\fR: Ausrichtung des Slits\. Horizontal oder Vertikal\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'
\fBClients\fR: Mit diesem Untermenue koennen die einzelnen Applikationen im Slit geordnet oder ausgeblendet werden\. Die Einstellungen werden in der Datei slitlist gespeichert\.
.RE
.SH "SLITLIST"
In der Datei slitlist speichert fluxbox die Reihenfolge der Applikationen in dem Slit\.
.sp
Diese Datei kann bei Bedarf von Hand editiert werden, sie ist eine einfache Liste der Fensternamen\. Die Datei sollte nicht editiert werden waehrend fluxbox laeuft, ansonsten koennten aenderungen verlorengehen\.
.sp
In der init Datei kann auch eine andere Datei als slitlist angegeben werden:
.sp
.sp
.RS 4
.nf
session\.session0\.slitlistFile: <Dateiname>
.fi
.RE
.SH "UMGEBUNGSVARIABLEN"
HOME: fluxbox nutzt die HOME Variable um die \.fluxbox/init Datei sowie Verzeichnisse fuer Farbschemata zu finden
.sp
DISPLAY: Wenn auf der Kommandozeile keine andere Anzeige angegeben wird nutzt fluxbox die in der Variable DISPLAY angegebene\.
.sp
Andere Umgebungsvariablen koennen von Vorteil sein\. Wenn zum Beispiel $TERM gesetzt ist, dann ist diese kann diese Variable von fluxbox verwendet werden, zum Beispiel mit einem Eintrag in die keys Datei:
.sp
.sp
.RS 4
.nf
Mod1 x ExecCommand :$TERM
.fi
.RE
Weiteres zu Umgebungsvariablen steht in der manpage der verwendeten Shell\.
.sp
.SH "SIGNALE"
fluxbox reagiert auf folgende Signale:
.sp
.sp
.RS 4
\h'-04'\(bu\h'+03'SIGHUP fluxbox laedt die Konfiguration
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'SIGUSR1 Erzwingt ein neues Einlesen der Konfiguration
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'SIGUSR2 Erzwingt ein neues Einlesen der Menuedatei
.RE
.SH "AUTOR UND DANKSAGUNGEN"
fluxbox wurde geschrieben und wird gepflegt von Henrik Kinnunen <fluxgen at fluxbox org> Simon Bowden <rathnor at fluxbox org> Mathias Gumz <akira at fluxbox org> Mark Tiefenbruck <mark at fluxbox org>
.sp
Zudem tragen viele Leute weltweit mit Patches, Bugreports, Uebersetzungen oder anderen Hilfestellungen zu dem Projekt bei\.
.sp
Blackbox wurde geschrieben und verwaltet durch: Brad Hughes <blackbox at alug org> Jeff Raven <jraven at psu edu>
.sp
Die offizielle fluxbox Webseite: http://www\.fluxbox\.org
.sp
Viele Farbschemata findet man unter: \- http://boxwhore\.org \- http://themes\.freshmeat\.net/
.sp
Diese Anleitung wurde geschrieben von:
.sp
.sp
.RS 4
\h'-04'\(bu\h'+03'Curt Micol <asenchi at asenchi com> (>fluxbox\-0\.9\.11)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Tobias Klausmann <klausman at users sourceforge net> (⇐fluxbox\-0\.9\.11)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Grubert <grubert at users sourceforge net> (fluxbox)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Matthew Hawkins <matt at mh dropbear id au> (blackbox)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Wilbert Berendsen <wbsoft at xs4all nl> (blackbox)
.RE
Deutsche Uebersetzung der Anleitung:
.sp
.sp
.RS 4
\h'-04'\(bu\h'+03'Christian (Fuchs) Loosli <develop at fuchsnet ch>
.RE
.SH "BUGS"
Fehler in fluxbox koennen entweder im #fluxbox irc channel im irc\.freenode\.net Netzwerk oder noch besser direkt auf http://sf\.net/projects/fluxbox gemeldet werden\. Zudem gibt es mehrere Mailinglisten\. Informationen dazu gibt es auf der offiziellen Projektseite\.
.sp
.SH "SIEHE AUCH"
bsetroot(1) fbsetbg(1) fbrun(1) fluxstyle(1)
.sp
