.\"
.\" Man page for fbsetroot
.\"
.\" Copyright (c) 2000 by Wilbert Berendsen <wbsoft@xs4all.nl>
.\" Copyright (c) 2004 by Curt "Asenchi" Micol <asenchi@asenchi.com>
.\" 
.\" This page was updated for Fluxbox by Curt "Asenchi" Micol on June 25, 2004
.\"
.\" Permission to use, copy, modify, and distribute this documentation for
.\" any purpose with or without fee is hereby granted, provided that the
.\" above copyright notice and this permission notice appear in all copies.
.\"
.\" THE DOCUMENTATION IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
.\" WARRANTIES WITH REGARD TO THIS DOCUMENTATION INCLUDING ALL IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
.\" AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
.\" DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
.\" PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
.\" TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
.\" PERFORMANCE OF THIS DOCUMENTATION
.\"
.TH fbsetroot 1 "July 8th, 2005" "0.9.13"
.SH NAME
fbsetroot \- a simple background utility used by the Fluxbox window manager, originally 
written for and by the original Blackbox window manager team.
.SH SYNOPSIS
.BR fbsetroot " \-help"
.br
.B fbsetroot
.RI "[ \-display " display " ] \-solid " color
.br
.B fbsetroot
.RI "[ \-display " display " ] \-mod " "x y" " \-fg " color " \-bg " color
.br
.B fbsetroot
.RI "[ \-display " display " ] \-gradient " texture " \-from " color " \-to " color
.SH DESCRIPTION
fbsetroot is a utility that can control the appearance of the root window in
three ways: Either give it a solid color, or write a two color modula pattern
to it, or render a gradient texture, based on two different colors.
.PP
fbsetroot resembles
.IR xsetroot (1)
in this functionality but it supports multiple screen displays, and gradient
textures the same way as Blackbox or Fluxbox does.
It doesn't handle cursors etc.
fbsetroot was originally part of the Blackbox package and was carried over with
the code that became Fluxbox. It was called bsetroot back in those days.
.SH OPTIONS
fbsetroot operates in three ways, you must choose one of the first 3 options:
.TP
.BI \-solid " color"
Sets the root window to specified color.
.TP
.BI \-mod " x y"
Creates a modula pattern. You must specify
.BR \-bg " and " \-fg
colors.
.TP
.BI \-gradient " texturestring"
Renders the specified texture string to the root window.
.RS
.PP
.I texturestring
may be one of:
.PP
.B Horizontal / Vertical / Diagonal / Crossdiagonal / Pipecross / Elliptic / Rectangle / Pyramid
.PP
Select one of these texture types, they only apply when
.B \-gradient
is specifed. You must also specify both a
.BR \-from " and a " \-to
color.
.RE
.TP
.BI \-display " display"
Tells fbsetroot to connect to the specified display.
.TP
.BI "\-bg, \-background " color
Background color.
Needed for
.B \-mod
patterns.
.TP
.BI "\-fg, \-foreground " color
Foreground color.
Needed for
.B \-mod
patterns.
.TP
.BI \-from " color"
Start color for rendering textures.
Needed for
.B \-gradient
operation mode.
.TP
.BI \-to " color"
Ending color for rendering textures.
Needed for
.B \-gradient
operation mode.
.TP
.B \-help
Prints version info and short help text.
.SH AUTHOR
fbsetroot is written and maintained by the Fluxbox Development Team
.PP
This manpage was modified by Curt "Asenchi" Micol <asenchi@asenchi.com> for
the Fluxbox window manager.
.hy
.SH SEE ALSO
.IR fluxbox (1)
.IR fbsetbg (1)
