.\" $Id$
.\"
.\" Copyright (c) 2004, Han Boetes <han@fluxbox.org>
.\"
.\" Permission to use, copy, modify, and distribute this documentation for
.\" any purpose with or without fee is hereby granted, provided that the
.\" above copyright notice and this permission notice appear in all copies.
.\"
.\" THE DOCUMENTATION IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
.\" WARRANTIES WITH REGARD TO THIS DOCUMENTATION INCLUDING ALL IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
.\" AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
.\" DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
.\" PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
.\" TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
.\" PERFORMANCE OF THIS DOCUMENTATION
.\"
.Dd Aug 10, 2004
.Dt STARTFLUXBOX 1
.Os
.Sh NAME
.Nm startfluxbox
.Nd "start a fluxbox session"
.Sh SYNOPSIS
.Nm startfluxbox
.Sh DESCRIPTION
.Nm
is a script which runs the file
.Bl -tag -width "~/.fluxbox/startup" -compact
.It Pa ~/.fluxbox/startup
.El
If it doesn't exist it will be generated.
.Pp
.Nm
should be started from your
.Bl -tag -width "~/.xinitrc" -compact
.It Pa ~/.xinitrc
if you use startx, or
.El
.Bl -tag -width "~/.xsession" -compact
.It Pa ~/.xsession
if you run a display manager, like xdm.
.Pp
.El
.Sh FILES
.Bl -tag -width "~/.fluxbox/startup" -compact
.It Pa ~/.fluxbox/startup
.El
This file contains all commands that should be executed before fluxbox
is started. The initial file contains helpful comments for beginners.
.Sh ONLINE DOCUMENTATION:
More extensive documentation for
.Nm
can be found at:
http://www.xs4all.nl/~hanb/software/fluxbox/startfluxbox.html
.Sh AUTHOR
The author of
.Nm
is Han Boetes <han@fluxbox.org>
