.\"
.\" Man page for Bsetroot
.\"
.\" Copyright (c) 2000 by Wilbert Berendsen <wbsoft@xs4all.nl>
.\"
.\" Permission to use, copy, modify, and distribute this documentation for
.\" any purpose with or without fee is hereby granted, provided that the
.\" above copyright notice and this permission notice appear in all copies.
.\"
.\" THE DOCUMENTATION IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
.\" WARRANTIES WITH REGARD TO THIS DOCUMENTATION INCLUDING ALL IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
.\" AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
.\" DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
.\" PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
.\" TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
.\" PERFORMANCE OF THIS DOCUMENTATION
.\"
.TH STARTFLUXBOX 1 "16 December 2003"
.SH NAME
startfluxbox \- customizable fluxbox start script
.SH SYNOPSIS
\fBstartfluxbox\fP
.SH DESCRIPTION
Before starting fluxbox this script can set background images, styles,
pixmaps, splash screens, keyboard layout and miscellaneous helper
applications.
.SH FILES
.TP
\fB~/.fluxbox/startup\fP
If this file exists it is executed before starting fluxbox.
.SH AUTHOR
This manpage was originally written by Bastian Kleineidam
<calvin@debian.org> for the Debian distribution of fluxbox
(but may be used by others).

The main author of fluxbox is Henrik Kinnunen <fluxgen@fluxbox.org>.
